create table if not exists costing.sales_allocation_quantity_driver_acceptance (
  id bigint generated by default as identity primary key,
  period_start date not null,
  source_valuation_date date not null,
  sku_id bigint not null,
  product_id bigint not null,
  source_refresh_run_id bigint not null references costing.costing_refresh_run(id),
  source_snapshot_id bigint not null references costing.sku_sales_allocation_basis_snapshot(id),
  monthly_driver_method text not null,
  monthly_driver_source text not null,
  monthly_driver_source_month date,
  assumption_id bigint,
  assumption_basis text,
  default_policy_id bigint,
  default_policy_scenario text,
  resolved_monthly_units numeric not null,
  resolved_monthly_base_qty numeric not null,
  evidence_fingerprint text not null,
  acceptance_status text not null default 'ACTIVE' check (acceptance_status in ('ACTIVE','INACTIVE')),
  acceptance_reason text not null,
  acceptance_note text,
  accepted_by uuid not null,
  accepted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_sales_allocation_driver_acceptance_active
on costing.sales_allocation_quantity_driver_acceptance(period_start,source_valuation_date,sku_id,evidence_fingerprint)
where acceptance_status='ACTIVE';

create index if not exists idx_sales_allocation_driver_acceptance_match
on costing.sales_allocation_quantity_driver_acceptance(period_start,source_valuation_date,sku_id,product_id,evidence_fingerprint,acceptance_status);

create or replace function costing.fn_sales_allocation_quantity_driver_fingerprint(
  p_sku_id bigint,
  p_product_id bigint,
  p_valuation_date date,
  p_monthly_driver_method text,
  p_monthly_driver_source text,
  p_monthly_driver_source_month date,
  p_assumption_id bigint,
  p_default_policy_id bigint,
  p_default_policy_scenario text,
  p_monthly_allocation_units numeric,
  p_monthly_allocation_base_qty numeric
) returns text
language sql immutable
as $f$
select md5(concat_ws('|',
  coalesce(p_sku_id::text,''),
  coalesce(p_product_id::text,''),
  coalesce(p_valuation_date::text,''),
  coalesce(p_monthly_driver_method,''),
  coalesce(p_monthly_driver_source,''),
  coalesce(p_monthly_driver_source_month::text,''),
  coalesce(p_assumption_id::text,''),
  coalesce(p_default_policy_id::text,''),
  coalesce(p_default_policy_scenario,''),
  coalesce(p_monthly_allocation_units::text,''),
  coalesce(p_monthly_allocation_base_qty::text,'')
));
$f$;

create or replace function costing.fn_sales_allocation_quantity_driver_review_status(p_snapshot_id bigint)
returns table(raw_status text,effective_status text,acceptance_id bigint,evidence_fingerprint text)
language sql stable security definer
set search_path to 'costing','public','pg_temp'
as $f$
with s as (
  select b.*,
    costing.fn_sales_allocation_quantity_driver_fingerprint(
      b.sku_id,b.product_id,b.valuation_date,b.monthly_driver_method,b.monthly_driver_source,
      b.monthly_driver_source_month,b.assumption_id,b.default_policy_id,b.default_policy_scenario,
      b.monthly_allocation_units,b.monthly_allocation_base_qty
    ) fp
  from costing.sku_sales_allocation_basis_snapshot b
  where b.id=p_snapshot_id
), a as (
  select a.id
  from s
  join costing.sales_allocation_quantity_driver_acceptance a
    on a.period_start=s.period_start
   and a.source_valuation_date=s.valuation_date
   and a.sku_id=s.sku_id
   and a.product_id=s.product_id
   and a.evidence_fingerprint=s.fp
   and a.acceptance_status='ACTIVE'
  order by a.accepted_at desc,a.id desc
  limit 1
)
select s.monthly_driver_status,
       case when s.monthly_driver_status='REVIEW_REQUIRED' and a.id is not null then 'READY'
            else s.monthly_driver_status end,
       a.id,
       s.fp
from s left join a on true;
$f$;

create or replace view costing.v_sales_allocation_quantity_driver_review_queue as
select
  b.period_start,b.valuation_date,b.refresh_run_id,b.id as source_snapshot_id,
  b.sku_id,b.product_id,b.product_name,b.pack_size,b.pack_uom,
  b.monthly_driver_method,b.monthly_driver_source,b.monthly_driver_source_month,
  b.monthly_driver_status as raw_monthly_driver_status,
  r.effective_status,
  b.allocation_resolution_status,b.allocation_resolution_note,
  b.assumption_id,b.assumption_basis,
  b.default_policy_id,b.default_policy_scenario,
  b.monthly_allocation_units,b.monthly_allocation_base_qty,
  r.evidence_fingerprint,r.acceptance_id,
  (r.acceptance_id is not null) as is_accepted
from costing.sku_sales_allocation_basis_snapshot b
cross join lateral costing.fn_sales_allocation_quantity_driver_review_status(b.id) r
where b.monthly_driver_status='REVIEW_REQUIRED';

create or replace function costing.rpc_accept_sales_allocation_quantity_driver_review(
  p_refresh_run_id bigint,
  p_sku_id bigint,
  p_acceptance_reason text,
  p_acceptance_note text default null
) returns table(
  acceptance_id bigint,period_start date,valuation_date date,refresh_run_id bigint,sku_id bigint,product_id bigint,
  monthly_driver_source text,default_policy_id bigint,default_policy_scenario text,assumption_id bigint,
  resolved_monthly_units numeric,evidence_fingerprint text,acceptance_status text,accepted_by uuid,accepted_at timestamptz,action_result text
)
language plpgsql security definer
set search_path to 'costing','public','pg_temp'
as $f$
declare
  v_user uuid:=auth.uid();
  v_reason text:=nullif(btrim(coalesce(p_acceptance_reason,'')),'');
  v_note text:=nullif(btrim(coalesce(p_acceptance_note,'')),'');
  v_run costing.costing_refresh_run%rowtype;
  v_s costing.sku_sales_allocation_basis_snapshot%rowtype;
  v_fp text;
  v_id bigint;
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  perform public.require_permission('costing-control-center',true);
  if p_refresh_run_id is null or p_sku_id is null then raise exception 'refresh_run_id and sku_id are required'; end if;
  if v_reason is null or length(v_reason)<5 then raise exception 'Acceptance reason must be at least 5 characters'; end if;

  select * into v_run from costing.costing_refresh_run where id=p_refresh_run_id;
  if not found then raise exception 'Costing refresh run % does not exist',p_refresh_run_id; end if;
  if v_run.overall_status<>'SUCCESS' then raise exception 'Quantity-driver review acceptance requires a successful immutable refresh run'; end if;

  select * into v_s
  from costing.sku_sales_allocation_basis_snapshot
  where refresh_run_id=p_refresh_run_id and sku_id=p_sku_id;
  if not found then raise exception 'Sales-allocation snapshot not found for run % SKU %',p_refresh_run_id,p_sku_id; end if;
  if v_s.monthly_driver_status<>'REVIEW_REQUIRED' then raise exception 'Only REVIEW_REQUIRED monthly quantity-driver evidence can be accepted'; end if;
  if v_s.monthly_allocation_units is null or v_s.monthly_allocation_units<=0
     or v_s.monthly_allocation_base_qty is null or v_s.monthly_allocation_base_qty<=0 then
    raise exception 'Quantity-driver acceptance requires positive resolved monthly quantity evidence';
  end if;
  if v_s.default_policy_id is null and v_s.assumption_id is null then
    raise exception 'Only governed default or governed SKU-assumption review evidence is accepted by this RPC';
  end if;

  v_fp:=costing.fn_sales_allocation_quantity_driver_fingerprint(
    v_s.sku_id,v_s.product_id,v_s.valuation_date,v_s.monthly_driver_method,v_s.monthly_driver_source,
    v_s.monthly_driver_source_month,v_s.assumption_id,v_s.default_policy_id,v_s.default_policy_scenario,
    v_s.monthly_allocation_units,v_s.monthly_allocation_base_qty
  );

  insert into costing.sales_allocation_quantity_driver_acceptance(
    period_start,source_valuation_date,sku_id,product_id,source_refresh_run_id,source_snapshot_id,
    monthly_driver_method,monthly_driver_source,monthly_driver_source_month,
    assumption_id,assumption_basis,default_policy_id,default_policy_scenario,
    resolved_monthly_units,resolved_monthly_base_qty,evidence_fingerprint,
    acceptance_status,acceptance_reason,acceptance_note,accepted_by,accepted_at,created_at,updated_at
  ) values (
    v_s.period_start,v_s.valuation_date,v_s.sku_id,v_s.product_id,v_s.refresh_run_id,v_s.id,
    v_s.monthly_driver_method,v_s.monthly_driver_source,v_s.monthly_driver_source_month,
    v_s.assumption_id,v_s.assumption_basis,v_s.default_policy_id,v_s.default_policy_scenario,
    v_s.monthly_allocation_units,v_s.monthly_allocation_base_qty,v_fp,
    'ACTIVE',v_reason,v_note,v_user,now(),now(),now()
  )
  on conflict (period_start,source_valuation_date,sku_id,evidence_fingerprint) where acceptance_status='ACTIVE'
  do update set source_refresh_run_id=excluded.source_refresh_run_id,source_snapshot_id=excluded.source_snapshot_id,
                acceptance_reason=excluded.acceptance_reason,acceptance_note=excluded.acceptance_note,
                accepted_by=excluded.accepted_by,accepted_at=excluded.accepted_at,updated_at=now()
  returning id into v_id;

  return query
  select a.id,a.period_start,a.source_valuation_date,a.source_refresh_run_id,a.sku_id,a.product_id,
         a.monthly_driver_source,a.default_policy_id,a.default_policy_scenario,a.assumption_id,
         a.resolved_monthly_units,a.evidence_fingerprint,a.acceptance_status,a.accepted_by,a.accepted_at,'ACCEPTED'::text
  from costing.sales_allocation_quantity_driver_acceptance a where a.id=v_id;
end;
$f$;

revoke all on function costing.rpc_accept_sales_allocation_quantity_driver_review(bigint,bigint,text,text) from public;
grant execute on function costing.rpc_accept_sales_allocation_quantity_driver_review(bigint,bigint,text,text) to authenticated;
grant select on costing.v_sales_allocation_quantity_driver_review_queue to authenticated;