-- Gate A: PLM PM-BOM temporal governance foundation
-- Additive only. No bootstrap data. No costing flip. No UI.
-- Overlap EXCLUDE covers APPROVED + SUPERSEDED.
-- As-of resolves APPROVED + SUPERSEDED only.

-- ---------------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------------

create table public.plm_bom_revision (
  id bigint generated by default as identity primary key,
  sku_id bigint not null references public.product_skus (id),
  revision_no integer not null,
  status text not null,
  effective_from date not null,
  effective_to date,
  source_tpl_id bigint references public.plm_tpl_header (id) on delete set null,
  frozen_reference_output_qty numeric not null,
  frozen_reference_output_uom_id bigint not null references public.inv_uom (id),
  frozen_process_loss_pct numeric not null,
  change_reason text,
  approval_reference text,
  supersedes_revision_id bigint references public.plm_bom_revision (id),
  content_hash text,
  frozen_at timestamptz,
  created_at timestamptz not null default clock_timestamp(),
  created_by uuid default auth.uid(),
  approved_at timestamptz,
  approved_by uuid,
  superseded_at timestamptz,
  superseded_by uuid,
  cancelled_at timestamptz,
  cancelled_by uuid,
  constraint plm_bom_revision_status_chk
    check (status = any (array['DRAFT'::text, 'APPROVED'::text, 'SUPERSEDED'::text, 'CANCELLED'::text])),
  constraint plm_bom_revision_dates_chk
    check ((effective_to is null) or (effective_to >= effective_from)),
  constraint plm_bom_revision_revision_no_chk
    check (revision_no > 0),
  constraint plm_bom_revision_qty_chk
    check (frozen_reference_output_qty > 0::numeric),
  constraint plm_bom_revision_loss_chk
    check (frozen_process_loss_pct >= 0::numeric),
  constraint plm_bom_revision_sku_rev_uq unique (sku_id, revision_no)
);

create table public.plm_bom_revision_line (
  id bigint generated by default as identity primary key,
  revision_id bigint not null references public.plm_bom_revision (id) on delete cascade,
  line_no integer not null,
  stock_item_id bigint not null references public.inv_stock_item (id),
  qty_per_reference_output numeric not null,
  uom_id bigint not null references public.inv_uom (id),
  wastage_pct numeric,
  is_optional boolean not null default false,
  is_override boolean not null default false,
  source_op text,
  remarks text,
  constraint plm_bom_revision_line_line_no_chk check (line_no > 0),
  constraint plm_bom_revision_line_qty_chk check (qty_per_reference_output > 0::numeric),
  constraint plm_bom_revision_line_wastage_chk
    check ((wastage_pct is null) or (wastage_pct >= 0::numeric)),
  constraint plm_bom_revision_line_rev_line_uq unique (revision_id, line_no),
  constraint plm_bom_revision_line_rev_item_uom_uq unique (revision_id, stock_item_id, uom_id)
);

create index ix_plm_bom_revision_sku_status_dates
  on public.plm_bom_revision (sku_id, status, effective_from, effective_to);

create index ix_plm_bom_revision_line_revision
  on public.plm_bom_revision_line (revision_id, line_no);

-- At most one open current APPROVED revision per SKU
create unique index uq_plm_bom_revision_one_open_approved
  on public.plm_bom_revision (sku_id)
  where (status = 'APPROVED' and effective_to is null);

-- Governed validity windows must not overlap (APPROVED + SUPERSEDED)
alter table public.plm_bom_revision
  add constraint plm_bom_revision_no_governed_overlap
  exclude using gist (
    sku_id with =,
    daterange(effective_from, coalesce(effective_to, 'infinity'::date), '[]') with &&
  )
  where (status = any (array['APPROVED'::text, 'SUPERSEDED'::text]));

comment on table public.plm_bom_revision is
  'Gate A governed SKU PM-BOM revision header. SUPERSEDED remains historically valid for as-of resolution.';
comment on table public.plm_bom_revision_line is
  'Frozen lines for a PM-BOM revision. Immutable once parent is APPROVED or SUPERSEDED.';

-- ---------------------------------------------------------------------------
-- 2. RLS: deny direct client table access; SECURITY DEFINER RPCs own writes
-- ---------------------------------------------------------------------------

alter table public.plm_bom_revision enable row level security;
alter table public.plm_bom_revision_line enable row level security;

revoke all on table public.plm_bom_revision from anon, authenticated;
revoke all on table public.plm_bom_revision_line from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3. Content hash
-- ---------------------------------------------------------------------------

create or replace function public.fn_plm_bom_revision_build_content_hash(
  p_sku_id bigint,
  p_effective_from date,
  p_frozen_reference_output_qty numeric,
  p_frozen_reference_output_uom_id bigint,
  p_frozen_process_loss_pct numeric,
  p_source_tpl_id bigint,
  p_lines jsonb
)
returns text
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_header text;
  v_lines text;
  v_line jsonb;
  v_parts text[] := array[]::text[];
  v_sorted jsonb;
begin
  if p_sku_id is null or p_effective_from is null then
    raise exception 'content_hash requires sku_id and effective_from';
  end if;

  v_header := concat_ws(
    '|',
    'sku=' || p_sku_id::text,
    'from=' || p_effective_from::text,
    'qty=' || trim(to_char(p_frozen_reference_output_qty, 'FM999999999999999999999999990.999999999999')),
    'uom=' || p_frozen_reference_output_uom_id::text,
    'loss=' || trim(to_char(p_frozen_process_loss_pct, 'FM999999999999999999999999990.999999999999')),
    'tpl=' || coalesce(p_source_tpl_id::text, '')
  );

  v_sorted := coalesce(
    (
      select jsonb_agg(x.elem order by (x.elem->>'line_no')::integer)
      from jsonb_array_elements(coalesce(p_lines, '[]'::jsonb)) as x(elem)
    ),
    '[]'::jsonb
  );

  for v_line in select * from jsonb_array_elements(v_sorted)
  loop
    v_parts := array_append(
      v_parts,
      concat_ws(
        '|',
        'ln=' || coalesce(v_line->>'line_no', ''),
        'item=' || coalesce(v_line->>'stock_item_id', ''),
        'qty=' || trim(to_char(coalesce((v_line->>'qty_per_reference_output')::numeric, 0), 'FM999999999999999999999999990.999999999999')),
        'uom=' || coalesce(v_line->>'uom_id', ''),
        'wast=' || case
          when v_line->>'wastage_pct' is null or v_line->>'wastage_pct' = '' then ''
          else trim(to_char((v_line->>'wastage_pct')::numeric, 'FM999999999999999999999999990.999999999999'))
        end,
        'opt=' || coalesce(v_line->>'is_optional', 'false'),
        'ovr=' || coalesce(v_line->>'is_override', 'false'),
        'op=' || coalesce(v_line->>'source_op', '')
      )
    );
  end loop;

  v_lines := array_to_string(v_parts, E'\n');
  return md5(v_header || E'\n' || v_lines);
end;
$function$;

create or replace function public.fn_plm_bom_revision_compute_content_hash(p_revision_id bigint)
returns text
language plpgsql
stable
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_h public.plm_bom_revision%rowtype;
  v_lines jsonb;
begin
  select * into v_h
  from public.plm_bom_revision
  where id = p_revision_id;

  if not found then
    raise exception 'Revision % not found', p_revision_id;
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'line_no', l.line_no,
        'stock_item_id', l.stock_item_id,
        'qty_per_reference_output', l.qty_per_reference_output,
        'uom_id', l.uom_id,
        'wastage_pct', l.wastage_pct,
        'is_optional', l.is_optional,
        'is_override', l.is_override,
        'source_op', l.source_op
      )
      order by l.line_no
    ),
    '[]'::jsonb
  )
  into v_lines
  from public.plm_bom_revision_line l
  where l.revision_id = p_revision_id;

  return public.fn_plm_bom_revision_build_content_hash(
    v_h.sku_id,
    v_h.effective_from,
    v_h.frozen_reference_output_qty,
    v_h.frozen_reference_output_uom_id,
    v_h.frozen_process_loss_pct,
    v_h.source_tpl_id,
    v_lines
  );
end;
$function$;

create or replace function public.fn_plm_bom_revision_verify_content_hash(p_revision_id bigint)
returns boolean
language sql
stable
set search_path to 'public', 'pg_temp'
as $function$
  select r.content_hash is not null
     and r.content_hash = public.fn_plm_bom_revision_compute_content_hash(r.id)
  from public.plm_bom_revision r
  where r.id = p_revision_id;
$function$;

-- ---------------------------------------------------------------------------
-- 4. Immutability (narrow GOVERNED bypass for approve transition only)
-- ---------------------------------------------------------------------------

create or replace function public.fn_plm_bom_revision_governed_context()
returns boolean
language sql
stable
set search_path to 'public', 'pg_temp'
as $function$
  select coalesce(current_setting('app.plm_bom_revision_mutate_context', true), '') = 'GOVERNED';
$function$;

create or replace function public.fn_plm_bom_revision_header_immutable()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_governed boolean := public.fn_plm_bom_revision_governed_context();
begin
  if tg_op = 'DELETE' then
    if old.status in ('APPROVED', 'SUPERSEDED') then
      raise exception 'Cannot delete % PM-BOM revision %', old.status, old.id;
    end if;
    return old;
  end if;

  if tg_op = 'UPDATE' then
    if old.status = 'CANCELLED' then
      raise exception 'Cannot update CANCELLED PM-BOM revision %', old.id;
    end if;

    if old.status = 'SUPERSEDED' then
      raise exception 'Cannot update SUPERSEDED PM-BOM revision %', old.id;
    end if;

    if old.status = 'APPROVED' then
      if not v_governed then
        raise exception 'Cannot update APPROVED PM-BOM revision % outside governed approval context', old.id;
      end if;

      -- Only controlled successor close transition: APPROVED -> SUPERSEDED
      if new.status is distinct from 'SUPERSEDED'
         or new.sku_id is distinct from old.sku_id
         or new.revision_no is distinct from old.revision_no
         or new.effective_from is distinct from old.effective_from
         or new.source_tpl_id is distinct from old.source_tpl_id
         or new.frozen_reference_output_qty is distinct from old.frozen_reference_output_qty
         or new.frozen_reference_output_uom_id is distinct from old.frozen_reference_output_uom_id
         or new.frozen_process_loss_pct is distinct from old.frozen_process_loss_pct
         or new.content_hash is distinct from old.content_hash
         or new.frozen_at is distinct from old.frozen_at
         or new.created_at is distinct from old.created_at
         or new.created_by is distinct from old.created_by
         or new.approved_at is distinct from old.approved_at
         or new.approved_by is distinct from old.approved_by
         or new.change_reason is distinct from old.change_reason
         or new.approval_reference is distinct from old.approval_reference
         or new.supersedes_revision_id is distinct from old.supersedes_revision_id
         or new.cancelled_at is distinct from old.cancelled_at
         or new.cancelled_by is distinct from old.cancelled_by
      then
        raise exception 'Governed update of APPROVED PM-BOM revision % may only supersede and close effective_to', old.id;
      end if;

      if new.effective_to is null then
        raise exception 'Superseding PM-BOM revision % requires effective_to', old.id;
      end if;

      if new.superseded_at is null then
        raise exception 'Superseding PM-BOM revision % requires superseded_at', old.id;
      end if;

      return new;
    end if;

    -- DRAFT updates (including DRAFT -> APPROVED / CANCELLED) allowed;
    -- DRAFT -> APPROVED must run under governed context from approve RPC.
    if old.status = 'DRAFT' and new.status = 'APPROVED' and not v_governed then
      raise exception 'Approving PM-BOM revision % requires governed approval RPC context', old.id;
    end if;
  end if;

  return new;
end;
$function$;

create or replace function public.fn_plm_bom_revision_line_immutable()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_status text;
  v_revision_id bigint;
begin
  v_revision_id := coalesce(new.revision_id, old.revision_id);

  select r.status into v_status
  from public.plm_bom_revision r
  where r.id = v_revision_id;

  if v_status is null then
    raise exception 'PM-BOM revision % not found for line guard', v_revision_id;
  end if;

  if v_status in ('APPROVED', 'SUPERSEDED') then
    raise exception 'Cannot % lines of % PM-BOM revision %', lower(tg_op), v_status, v_revision_id;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$function$;

create trigger trg_plm_bom_revision_immutable
  before update or delete on public.plm_bom_revision
  for each row
  execute function public.fn_plm_bom_revision_header_immutable();

create trigger trg_plm_bom_revision_line_immutable
  before insert or update or delete on public.plm_bom_revision_line
  for each row
  execute function public.fn_plm_bom_revision_line_immutable();

-- ---------------------------------------------------------------------------
-- 5. As-of resolvers (no current-state PLM fallback)
-- ---------------------------------------------------------------------------

create or replace function public.plm_sku_bom_revision_as_of(
  p_sku_id bigint,
  p_as_of date
)
returns public.plm_bom_revision
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_count integer;
  v_row public.plm_bom_revision%rowtype;
begin
  if p_sku_id is null then
    raise exception 'p_sku_id is required';
  end if;
  if p_as_of is null then
    raise exception 'p_as_of is required';
  end if;

  select count(*)::integer into v_count
  from public.plm_bom_revision r
  where r.sku_id = p_sku_id
    and r.status in ('APPROVED', 'SUPERSEDED')
    and r.effective_from <= p_as_of
    and (r.effective_to is null or r.effective_to >= p_as_of);

  if v_count > 1 then
    raise exception 'AMBIGUOUS_PM_BOM_REVISION: sku_id=% as_of=% matched % governed revisions',
      p_sku_id, p_as_of, v_count;
  end if;

  if v_count = 0 then
    return null;
  end if;

  select r.* into v_row
  from public.plm_bom_revision r
  where r.sku_id = p_sku_id
    and r.status in ('APPROVED', 'SUPERSEDED')
    and r.effective_from <= p_as_of
    and (r.effective_to is null or r.effective_to >= p_as_of);

  return v_row;
end;
$function$;

create or replace function public.plm_sku_bom_lines_as_of(
  p_sku_id bigint,
  p_as_of date
)
returns table (
  revision_id bigint,
  revision_no integer,
  effective_from date,
  effective_to date,
  content_hash text,
  line_no integer,
  stock_item_id bigint,
  stock_item_name text,
  qty_per_reference_output numeric,
  uom_id bigint,
  uom_code text,
  wastage_pct numeric,
  is_optional boolean,
  is_override boolean,
  source_op text,
  remarks text
)
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_rev public.plm_bom_revision%rowtype;
begin
  v_rev := public.plm_sku_bom_revision_as_of(p_sku_id, p_as_of);
  if v_rev.id is null then
    return;
  end if;

  return query
  select
    v_rev.id,
    v_rev.revision_no,
    v_rev.effective_from,
    v_rev.effective_to,
    v_rev.content_hash,
    l.line_no,
    l.stock_item_id,
    i.name,
    l.qty_per_reference_output,
    l.uom_id,
    u.code,
    l.wastage_pct,
    l.is_optional,
    l.is_override,
    l.source_op,
    l.remarks
  from public.plm_bom_revision_line l
  left join public.inv_stock_item i on i.id = l.stock_item_id
  left join public.inv_uom u on u.id = l.uom_id
  where l.revision_id = v_rev.id
  order by l.line_no;
end;
$function$;

create or replace function public.plm_sku_requirement_unit_as_of(p_as_of date)
returns table (
  sku_id bigint,
  product_id bigint,
  product_name text,
  pack_size numeric,
  pack_uom text,
  revision_id bigint,
  revision_no integer,
  stock_item_id bigint,
  stock_item_name text,
  uom_id bigint,
  uom_code text,
  qty_per_reference_output numeric,
  wastage_pct numeric,
  is_optional boolean,
  is_override boolean,
  qty_required_unit_final numeric,
  content_hash text
)
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  if p_as_of is null then
    raise exception 'p_as_of is required';
  end if;

  return query
  select
    s.id,
    s.product_id,
    p.item,
    s.pack_size,
    s.uom,
    l.revision_id,
    l.revision_no,
    l.stock_item_id,
    l.stock_item_name,
    l.uom_id,
    l.uom_code,
    l.qty_per_reference_output,
    l.wastage_pct,
    l.is_optional,
    l.is_override,
    l.qty_per_reference_output * (1::numeric + coalesce(l.wastage_pct, 0::numeric)),
    l.content_hash
  from public.product_skus s
  left join public.products p on p.id = s.product_id
  join lateral public.plm_sku_bom_lines_as_of(s.id, p_as_of) l on true;
end;
$function$;

-- ---------------------------------------------------------------------------
-- 6. Lifecycle RPCs
-- ---------------------------------------------------------------------------

create or replace function public.rpc_plm_bom_revision_create_draft(
  p_sku_id bigint,
  p_effective_from date default current_date
)
returns bigint
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_revision_id bigint;
  v_revision_no integer;
  v_tpl_id bigint;
  v_qty numeric;
  v_uom_id bigint;
  v_loss numeric;
  v_line_count integer := 0;
begin
  perform public.require_permission('module:pm-templates', true);

  if p_sku_id is null then
    raise exception 'p_sku_id is required';
  end if;
  if p_effective_from is null then
    raise exception 'p_effective_from is required';
  end if;

  if not exists (select 1 from public.product_skus s where s.id = p_sku_id) then
    raise exception 'SKU % not found', p_sku_id;
  end if;

  perform pg_advisory_xact_lock(87201401, (abs(p_sku_id) % 2147483647)::integer);

  select m.tpl_id into v_tpl_id
  from public.plm_sku_pack_map m
  where m.sku_id = p_sku_id;

  select h.reference_output_qty, h.reference_output_uom_id, h.process_loss_pct
  into v_qty, v_uom_id, v_loss
  from public.plm_bom_header h
  where h.sku_id = p_sku_id;

  if v_qty is null then
    select t.reference_output_qty, t.reference_output_uom_id, t.process_loss_pct
    into v_qty, v_uom_id, v_loss
    from public.plm_tpl_header t
    where t.id = v_tpl_id;
  end if;

  if v_qty is null or v_uom_id is null or v_loss is null then
    raise exception 'Cannot freeze draft for SKU %: missing reference output / process loss from compiled BOM or mapped template', p_sku_id;
  end if;

  select coalesce(max(r.revision_no), 0) + 1
  into v_revision_no
  from public.plm_bom_revision r
  where r.sku_id = p_sku_id;

  insert into public.plm_bom_revision (
    sku_id,
    revision_no,
    status,
    effective_from,
    source_tpl_id,
    frozen_reference_output_qty,
    frozen_reference_output_uom_id,
    frozen_process_loss_pct,
    created_by
  ) values (
    p_sku_id,
    v_revision_no,
    'DRAFT',
    p_effective_from,
    v_tpl_id,
    v_qty,
    v_uom_id,
    v_loss,
    auth.uid()
  )
  returning id into v_revision_id;

  insert into public.plm_bom_revision_line (
    revision_id,
    line_no,
    stock_item_id,
    qty_per_reference_output,
    uom_id,
    wastage_pct,
    is_optional,
    is_override,
    source_op
  )
  select
    v_revision_id,
    row_number() over (order by e.stock_item_id, e.uom_id)::integer,
    e.stock_item_id,
    e.qty_per_reference_output,
    e.uom_id,
    e.wastage_pct,
    coalesce(e.is_optional, false),
    coalesce(e.is_override, false),
    case when coalesce(e.is_override, false) then 'override' else 'template' end
  from public.plm_sku_bom_effective(p_sku_id) e;

  get diagnostics v_line_count = row_count;

  if v_line_count = 0 then
    raise exception 'Cannot create draft for SKU %: effective PM BOM has no lines', p_sku_id;
  end if;

  return v_revision_id;
end;
$function$;

create or replace function public.rpc_plm_bom_revision_cancel(p_revision_id bigint)
returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_row public.plm_bom_revision%rowtype;
begin
  perform public.require_permission('module:pm-templates', true);

  select * into v_row
  from public.plm_bom_revision
  where id = p_revision_id
  for update;

  if not found then
    raise exception 'Revision % not found', p_revision_id;
  end if;

  if v_row.status <> 'DRAFT' then
    raise exception 'Only DRAFT revisions may be cancelled (revision % is %)', p_revision_id, v_row.status;
  end if;

  update public.plm_bom_revision
  set status = 'CANCELLED',
      cancelled_at = clock_timestamp(),
      cancelled_by = auth.uid()
  where id = p_revision_id;
end;
$function$;

create or replace function public.rpc_plm_bom_revision_approve(
  p_revision_id bigint,
  p_effective_from date,
  p_change_reason text,
  p_approval_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_draft public.plm_bom_revision%rowtype;
  v_prior public.plm_bom_revision%rowtype;
  v_reason text := nullif(btrim(p_change_reason), '');
  v_ref text := nullif(btrim(p_approval_reference), '');
  v_hash text;
  v_line_count integer;
  v_actor uuid := auth.uid();
begin
  perform public.require_permission('module:pm-templates', true);

  if p_revision_id is null then
    raise exception 'p_revision_id is required';
  end if;
  if p_effective_from is null then
    raise exception 'p_effective_from is required';
  end if;
  if v_reason is null then
    raise exception 'change_reason is required';
  end if;
  if v_ref is not null and upper(v_ref) in ('-', '—', 'NA', 'N/A', 'AUTO', 'MIGRATION') then
    raise exception 'A meaningful approval_reference is required when provided';
  end if;

  select * into v_draft
  from public.plm_bom_revision
  where id = p_revision_id
  for update;

  if not found then
    raise exception 'Revision % not found', p_revision_id;
  end if;

  perform pg_advisory_xact_lock(87201401, (abs(v_draft.sku_id) % 2147483647)::integer);

  -- Re-lock draft after sku lock
  select * into v_draft
  from public.plm_bom_revision
  where id = p_revision_id
  for update;

  if v_draft.status <> 'DRAFT' then
    raise exception 'Only DRAFT revisions may be approved (revision % is %)', p_revision_id, v_draft.status;
  end if;

  select count(*)::integer into v_line_count
  from public.plm_bom_revision_line l
  where l.revision_id = p_revision_id;

  if v_line_count = 0 then
    raise exception 'Draft revision % has no lines', p_revision_id;
  end if;

  -- Lock all revisions for this SKU against concurrent approval
  perform 1
  from public.plm_bom_revision r
  where r.sku_id = v_draft.sku_id
  for update;

  select * into v_prior
  from public.plm_bom_revision r
  where r.sku_id = v_draft.sku_id
    and r.status = 'APPROVED'
    and r.effective_to is null
  for update;

  if found then
    if p_effective_from <= v_prior.effective_from then
      raise exception 'Successor effective_from (%) must be after prior open APPROVED effective_from (%)',
        p_effective_from, v_prior.effective_from;
    end if;
  end if;

  -- Prevalidate successor open window vs other governed rows
  -- (prior open APPROVED is excluded; it will be closed in this transaction)
  if exists (
    select 1
    from public.plm_bom_revision r
    where r.sku_id = v_draft.sku_id
      and r.id <> p_revision_id
      and (v_prior.id is null or r.id <> v_prior.id)
      and r.status in ('APPROVED', 'SUPERSEDED')
      and daterange(r.effective_from, coalesce(r.effective_to, 'infinity'::date), '[]')
          && daterange(p_effective_from, 'infinity'::date, '[]')
  ) then
    raise exception 'Governed PM-BOM revision overlap would occur for sku_id=% from %',
      v_draft.sku_id, p_effective_from;
  end if;

  perform set_config('app.plm_bom_revision_mutate_context', 'GOVERNED', true);

  if v_prior.id is not null then
    update public.plm_bom_revision
    set status = 'SUPERSEDED',
        effective_to = p_effective_from - 1,
        superseded_at = clock_timestamp(),
        superseded_by = v_actor
    where id = v_prior.id;
  end if;

  -- Apply effective_from before hash so hash matches stored approved content
  update public.plm_bom_revision
  set effective_from = p_effective_from,
      change_reason = v_reason,
      approval_reference = v_ref
  where id = p_revision_id;

  v_hash := public.fn_plm_bom_revision_compute_content_hash(p_revision_id);

  update public.plm_bom_revision
  set status = 'APPROVED',
      approved_at = clock_timestamp(),
      approved_by = v_actor,
      frozen_at = clock_timestamp(),
      content_hash = v_hash,
      supersedes_revision_id = v_prior.id
  where id = p_revision_id;

  perform set_config('app.plm_bom_revision_mutate_context', '', true);

  return jsonb_build_object(
    'revision_id', p_revision_id,
    'sku_id', v_draft.sku_id,
    'status', 'APPROVED',
    'effective_from', p_effective_from,
    'content_hash', v_hash,
    'superseded_revision_id', v_prior.id,
    'prior_effective_to', case when v_prior.id is not null then p_effective_from - 1 else null end
  );
exception
  when others then
    perform set_config('app.plm_bom_revision_mutate_context', '', true);
    raise;
end;
$function$;

create or replace function public.rpc_plm_bom_revision_list(p_sku_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  perform public.require_permission('module:pm-templates', false);

  if p_sku_id is null then
    raise exception 'p_sku_id is required';
  end if;

  return coalesce(
    (
      select jsonb_agg(to_jsonb(r) order by r.revision_no desc)
      from public.plm_bom_revision r
      where r.sku_id = p_sku_id
    ),
    '[]'::jsonb
  );
end;
$function$;

create or replace function public.rpc_plm_bom_revision_get(p_revision_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_row jsonb;
begin
  perform public.require_permission('module:pm-templates', false);

  select to_jsonb(r) into v_row
  from public.plm_bom_revision r
  where r.id = p_revision_id;

  if v_row is null then
    raise exception 'Revision % not found', p_revision_id;
  end if;

  return v_row;
end;
$function$;

create or replace function public.rpc_plm_bom_revision_list_lines(p_revision_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  perform public.require_permission('module:pm-templates', false);

  if not exists (select 1 from public.plm_bom_revision r where r.id = p_revision_id) then
    raise exception 'Revision % not found', p_revision_id;
  end if;

  return coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', l.id,
          'revision_id', l.revision_id,
          'line_no', l.line_no,
          'stock_item_id', l.stock_item_id,
          'stock_item_name', i.name,
          'qty_per_reference_output', l.qty_per_reference_output,
          'uom_id', l.uom_id,
          'uom_code', u.code,
          'wastage_pct', l.wastage_pct,
          'is_optional', l.is_optional,
          'is_override', l.is_override,
          'source_op', l.source_op,
          'remarks', l.remarks
        )
        order by l.line_no
      )
      from public.plm_bom_revision_line l
      left join public.inv_stock_item i on i.id = l.stock_item_id
      left join public.inv_uom u on u.id = l.uom_id
      where l.revision_id = p_revision_id
    ),
    '[]'::jsonb
  );
end;
$function$;

-- ---------------------------------------------------------------------------
-- 7. Grants
-- ---------------------------------------------------------------------------

grant execute on function public.fn_plm_bom_revision_build_content_hash(bigint, date, numeric, bigint, numeric, bigint, jsonb) to authenticated;
grant execute on function public.fn_plm_bom_revision_compute_content_hash(bigint) to authenticated;
grant execute on function public.fn_plm_bom_revision_verify_content_hash(bigint) to authenticated;
grant execute on function public.plm_sku_bom_revision_as_of(bigint, date) to authenticated;
grant execute on function public.plm_sku_bom_lines_as_of(bigint, date) to authenticated;
grant execute on function public.plm_sku_requirement_unit_as_of(date) to authenticated;
grant execute on function public.rpc_plm_bom_revision_create_draft(bigint, date) to authenticated;
grant execute on function public.rpc_plm_bom_revision_cancel(bigint) to authenticated;
grant execute on function public.rpc_plm_bom_revision_approve(bigint, date, text, text) to authenticated;
grant execute on function public.rpc_plm_bom_revision_list(bigint) to authenticated;
grant execute on function public.rpc_plm_bom_revision_get(bigint) to authenticated;
grant execute on function public.rpc_plm_bom_revision_list_lines(bigint) to authenticated;

revoke all on function public.fn_plm_bom_revision_governed_context() from public, anon, authenticated;
revoke all on function public.fn_plm_bom_revision_header_immutable() from public, anon, authenticated;
revoke all on function public.fn_plm_bom_revision_line_immutable() from public, anon, authenticated;
