-- SOURCE-CONTROL PARITY
-- Already applied live as:
--   20260915085019_canonical_sales_planning_fallback_units
-- DO NOT reapply to production.
--
-- Temporary shared Sales Planning Fallback Units (investigation artifact).
-- Prospective cutover removes active costing authority; objects retained for audit.

create table if not exists costing.sales_planning_fallback_unit_policy (
  id bigint generated by default as identity primary key,
  default_sales_units numeric not null,
  effective_from date not null,
  status text not null default 'APPROVED'::text,
  reason text not null,
  approval_reference text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default clock_timestamp(),
  constraint sales_planning_fallback_unit_policy_default_sales_units_check
    check (default_sales_units > 0::numeric),
  constraint sales_planning_fallback_unit_policy_status_check
    check (status = any (array['APPROVED'::text, 'CANCELLED'::text]))
);

create unique index if not exists uq_sales_planning_fallback_effective_approved
  on costing.sales_planning_fallback_unit_policy (effective_from)
  where status = 'APPROVED';

create or replace function costing.fn_resolve_sales_planning_fallback_units_as_of(p_valuation_date date)
returns table (
  policy_id bigint,
  default_sales_units numeric,
  effective_from date,
  resolution_status text,
  qualifying_policy_count bigint,
  resolution_note text
)
language sql
stable
security definer
set search_path to 'costing', 'public', 'pg_temp'
as $function$
with eligible as (
  select p.*
  from costing.sales_planning_fallback_unit_policy p
  where p.status = 'APPROVED'
    and p.effective_from <= p_valuation_date
), latest_date as (
  select max(effective_from) as effective_from from eligible
), candidates as (
  select e.* from eligible e join latest_date l on l.effective_from = e.effective_from
), s as (select count(*)::bigint as n from candidates)
select
  case when s.n = 1 then c.id end,
  case when s.n = 1 then c.default_sales_units end,
  case when s.n = 1 then c.effective_from end,
  case
    when p_valuation_date is null then 'INVALID_CONTEXT'
    when s.n = 0 then 'MISSING'
    when s.n > 1 then 'AMBIGUOUS'
    else 'RESOLVED'
  end,
  s.n,
  case
    when p_valuation_date is null then 'Valuation date is required.'
    when s.n = 0 then 'No canonical Sales Planning Fallback Unit policy is effective on the valuation date.'
    when s.n > 1 then 'Multiple canonical Sales Planning Fallback Unit policies share the latest effective date.'
    else format('Canonical Sales Planning Fallback Unit policy %s resolves %s units.', c.id, c.default_sales_units)
  end
from s
left join candidates c on s.n = 1;
$function$;

comment on table costing.sales_planning_fallback_unit_policy is
  'DEPRECATED AUDIT ARTIFACT. Temporary shared fallback. Not authoritative after CSA scenario-owned cutover.';
comment on function costing.fn_resolve_sales_planning_fallback_units_as_of(date) is
  'DEPRECATED. Temporary shared fallback resolver.';
