-- SOURCE-CONTROL PARITY — already applied in production as
--   20260910154540_regional_sales_default_policy_foundation
-- Captured 2026-09-11 from the linked project (qhmoqtxpeasamtlxaoak)
-- via information_schema / pg_get_functiondef / pg_get_constraintdef /
-- pg_get_triggerdef. Bodies below are the live definitions.
--
-- DO NOT apply this migration to production. Production already has it.
-- This file exists so repository schema history matches live
-- supabase_migrations.schema_migrations.

create table costing.regional_sales_allocation_default_policy (
  id bigint generated by default as identity primary key,
  scenario_code text not null,
  region_code text not null,
  default_sales_units numeric not null,
  effective_from date not null,
  effective_to date,
  status text not null default 'APPROVED'::text,
  reason text not null,
  approval_reference text,
  previous_policy_id bigint,
  created_at timestamp with time zone not null default clock_timestamp(),
  created_by uuid default auth.uid(),
  closed_at timestamp with time zone,
  closed_by uuid,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  cancellation_reason text,
  cancellation_approval_reference text,
  constraint regional_sales_default_dates_chk
    check ((effective_to is null) or (effective_to >= effective_from)),
  constraint regional_sales_default_region_chk
    check (region_code = any (array['IK'::text, 'OK'::text])),
  constraint regional_sales_default_scenario_chk
    check (
      scenario_code = any (
        array[
          'NO_ELIGIBLE_REGIONAL_HISTORY'::text,
          'NO_POSITIVE_REGIONAL_HISTORY'::text
        ]
      )
    ),
  constraint regional_sales_default_status_chk
    check (
      status = any (array['APPROVED'::text, 'CLOSED'::text, 'CANCELLED'::text])
    ),
  constraint regional_sales_default_units_chk
    check (default_sales_units > (0)::numeric),
  constraint regional_sales_allocation_default_polic_previous_policy_id_fkey
    foreign key (previous_policy_id)
    references costing.regional_sales_allocation_default_policy(id)
);

create index ix_regional_sales_default_policy_lookup
  on costing.regional_sales_allocation_default_policy
  using btree (scenario_code, region_code, effective_from, effective_to, status);

CREATE OR REPLACE FUNCTION costing.fn_guard_regional_sales_default_policy_overlap()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'costing', 'public', 'pg_temp'
AS $function$
begin
    if new.status <> 'APPROVED' then return new; end if;
    if exists (
        select 1
        from costing.regional_sales_allocation_default_policy p
        where p.scenario_code = new.scenario_code
          and p.region_code = new.region_code
          and p.status = 'APPROVED'
          and p.id <> coalesce(new.id,-1)
          and daterange(p.effective_from,coalesce(p.effective_to + 1,'infinity'::date),'[)')
              && daterange(new.effective_from,coalesce(new.effective_to + 1,'infinity'::date),'[)')
    ) then
        raise exception 'An approved regional sales-allocation default policy already overlaps scenario % / region % for the requested effective period.', new.scenario_code,new.region_code;
    end if;
    return new;
end;
$function$;

CREATE TRIGGER trg_guard_regional_sales_default_policy_overlap
  BEFORE INSERT OR UPDATE ON costing.regional_sales_allocation_default_policy
  FOR EACH ROW
  EXECUTE FUNCTION costing.fn_guard_regional_sales_default_policy_overlap();

CREATE OR REPLACE FUNCTION costing.fn_resolve_regional_sales_default_policy_as_of(p_scenario_code text, p_region_code text, p_valuation_date date)
 RETURNS TABLE(policy_id bigint, scenario_code text, region_code text, default_sales_units numeric, effective_from date, effective_to date, resolution_status text, qualifying_policy_count bigint, resolution_note text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'costing', 'public', 'pg_temp'
AS $function$
with n as (
    select upper(btrim(coalesce(p_scenario_code,''))) scenario_code,
           upper(btrim(coalesce(p_region_code,''))) region_code,
           p_valuation_date valuation_date
), c as (
    select p.*
    from costing.regional_sales_allocation_default_policy p cross join n
    where p.scenario_code=n.scenario_code
      and p.region_code=n.region_code
      and p.status in ('APPROVED','CLOSED')
      and p.effective_from <= n.valuation_date
      and (p.effective_to is null or p.effective_to >= n.valuation_date)
), s as (select count(*)::bigint qualifying_count from c)
select case when s.qualifying_count=1 then c.id end,
       n.scenario_code,n.region_code,
       case when s.qualifying_count=1 then c.default_sales_units end,
       case when s.qualifying_count=1 then c.effective_from end,
       case when s.qualifying_count=1 then c.effective_to end,
       case
         when p_valuation_date is null then 'INVALID_CONTEXT'
         when n.scenario_code not in ('NO_ELIGIBLE_REGIONAL_HISTORY','NO_POSITIVE_REGIONAL_HISTORY') then 'INVALID_SCENARIO'
         when n.region_code not in ('IK','OK') then 'INVALID_REGION'
         when s.qualifying_count=0 then 'MISSING'
         when s.qualifying_count>1 then 'AMBIGUOUS'
         else 'RESOLVED'
       end,
       s.qualifying_count,
       case
         when p_valuation_date is null then 'Valuation date is required.'
         when n.scenario_code not in ('NO_ELIGIBLE_REGIONAL_HISTORY','NO_POSITIVE_REGIONAL_HISTORY') then 'Regional sales-allocation default scenario is invalid.'
         when n.region_code not in ('IK','OK') then 'Region must be IK or OK.'
         when s.qualifying_count=0 then 'No governed regional default allocation-volume policy is effective on the valuation date.'
         when s.qualifying_count>1 then 'Multiple governed regional default policies overlap on the valuation date.'
         else 'Regional default allocation-volume policy resolved.'
       end
from n cross join s left join c on s.qualifying_count=1;
$function$;

CREATE OR REPLACE FUNCTION costing.fn_resolve_regional_default_commercial_value(p_sku_id bigint, p_region_code text, p_total_units numeric, p_effective_date date)
 RETURNS TABLE(resolution_status text, resolution_note text, assumed_paid_units numeric, assumed_free_units numeric, assumed_total_units numeric, assumed_total_base_qty numeric, resolved_sales_value numeric, value_resolution_source text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'costing', 'public', 'pg_temp'
AS $function$
declare
    v_region text := upper(btrim(coalesce(p_region_code,'')));
    v_base record; v_scheme record; v_mrp record; v_price record;
    v_paid numeric; v_free numeric; v_total numeric; v_base_qty numeric;
    v_mrp_value numeric; v_basic numeric; v_discount numeric; v_billed numeric; v_value numeric;
begin
    if p_sku_id is null or p_effective_date is null or p_total_units is null or p_total_units<=0 or v_region not in ('IK','OK') then
        return query select 'INVALID_CONTEXT','SKU, region, positive total units and effective date are required.',null::numeric,null::numeric,null::numeric,null::numeric,null::numeric,null::text;
        return;
    end if;

    select * into v_base from costing.fn_resolve_sku_commercial_base_context(p_sku_id);
    if v_base.resolution_status is distinct from 'RESOLVED' then
        return query select 'BLOCKED',coalesce(v_base.resolution_note,'SKU commercial base context is unresolved.'),null::numeric,null::numeric,null::numeric,null::numeric,null::numeric,null::text;
        return;
    end if;

    select * into v_scheme from costing.fn_resolve_selected_scheme_policy_as_of(p_sku_id,v_region,p_effective_date);
    if v_scheme.resolution_status not in ('RESOLVED_POLICY','DEFAULT_NO_SCHEME')
       or v_scheme.paid_qty is null or v_scheme.paid_qty<=0
       or v_scheme.free_qty is null or v_scheme.free_qty<0
       or v_scheme.total_qty is null or v_scheme.total_qty<=0 then
        return query select 'BLOCKED',coalesce(v_scheme.resolution_note,'Regional scheme context is unresolved.'),null::numeric,null::numeric,null::numeric,null::numeric,null::numeric,null::text;
        return;
    end if;

    -- Policy quantity means total physical sales units. Split paid/free proportionally to the governed scheme.
    v_total := p_total_units;
    v_paid := v_total * v_scheme.paid_qty / v_scheme.total_qty;
    v_free := v_total - v_paid;
    v_base_qty := v_total * v_base.sku_base_qty_per_unit;

    select * into v_mrp from costing.fn_resolve_sku_mrp_as_of(p_sku_id,p_effective_date);
    if v_mrp.resolution_status is distinct from 'RESOLVED' then
        return query select 'BLOCKED',coalesce(v_mrp.resolution_note,'MRP policy is unresolved.'),v_paid,v_free,v_total,v_base_qty,null::numeric,null::text;
        return;
    end if;
    v_mrp_value := case when v_region='IK' then v_mrp.mrp_ik else v_mrp.mrp_ok end;
    if v_mrp_value is null or v_mrp_value<0 then
        return query select 'BLOCKED','Resolved regional MRP is missing or invalid.',v_paid,v_free,v_total,v_base_qty,null::numeric,null::text;
        return;
    end if;

    select * into v_price from costing.fn_resolve_sku_selling_price_policy_as_of(p_sku_id,p_effective_date);
    if v_price.resolution_status is distinct from 'RESOLVED' or v_price.gst_percent is null or v_price.gst_percent<0 then
        return query select 'BLOCKED',coalesce(v_price.resolution_note,'Selling-price policy is unresolved.'),v_paid,v_free,v_total,v_base_qty,null::numeric,null::text;
        return;
    end if;

    v_basic := v_mrp_value / (1 + v_price.gst_percent/100.0);
    v_discount := case
        when v_region='IK' and v_price.ik_discount_amount is not null then v_price.ik_discount_amount
        when v_region='OK' and v_price.ok_discount_amount is not null then v_price.ok_discount_amount
        when v_region='IK' and v_price.ik_discount_percent is not null then v_basic * v_price.ik_discount_percent/100.0
        when v_region='OK' and v_price.ok_discount_percent is not null then v_basic * v_price.ok_discount_percent/100.0
        else null::numeric end;
    if v_discount is null or v_discount<0 or v_discount>v_basic then
        return query select 'BLOCKED','Standard regional discount could not be resolved to a valid amount.',v_paid,v_free,v_total,v_base_qty,null::numeric,null::text;
        return;
    end if;
    v_billed := v_basic-v_discount;
    v_value := v_paid*v_billed;
    return query select 'READY','Regional default commercial value resolved from governed scheme, MRP, GST and selling-price policies.',v_paid,v_free,v_total,v_base_qty,v_value,'GOVERNED_REGIONAL_DEFAULT_STANDARD_POLICY';
exception when others then
    return query select 'BLOCKED',sqlerrm,null::numeric,null::numeric,null::numeric,null::numeric,null::numeric,null::text;
end;
$function$;

CREATE OR REPLACE FUNCTION public.rpc_get_regional_sales_allocation_default_policies()
 RETURNS SETOF costing.regional_sales_allocation_default_policy
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'costing', 'pg_temp'
AS $function$
begin
    perform public.require_permission('module:pricing-policy-manager',false);
    if auth.uid() is null then raise exception 'Authenticated user context is required'; end if;
    return query select * from costing.regional_sales_allocation_default_policy order by scenario_code,region_code,effective_from desc,id desc;
end;
$function$;

CREATE OR REPLACE FUNCTION public.rpc_set_regional_sales_allocation_default_policy(p_scenario_code text, p_region_code text, p_default_sales_units numeric, p_effective_from date, p_reason text, p_approval_reference text DEFAULT NULL::text)
 RETURNS TABLE(policy_id bigint, scenario_code text, region_code text, default_sales_units numeric, effective_from date, effective_to date, status text, previous_policy_id bigint, created_at timestamp with time zone, created_by uuid)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'costing', 'pg_temp'
AS $function$
declare
    v_actor uuid; v_scenario text; v_region text; v_reason text; v_ref text;
    v_previous costing.regional_sales_allocation_default_policy%rowtype;
    v_saved costing.regional_sales_allocation_default_policy%rowtype;
begin
    perform public.require_permission('module:pricing-policy-manager',true);
    v_actor:=auth.uid();
    if v_actor is null then raise exception 'Authenticated user context is required'; end if;
    v_scenario:=upper(btrim(coalesce(p_scenario_code,'')));
    v_region:=upper(btrim(coalesce(p_region_code,'')));
    if v_scenario not in ('NO_ELIGIBLE_REGIONAL_HISTORY','NO_POSITIVE_REGIONAL_HISTORY') then raise exception 'Invalid regional allocation policy scenario.'; end if;
    if v_region not in ('IK','OK') then raise exception 'Region must be IK or OK.'; end if;
    if p_default_sales_units is null or p_default_sales_units<=0 then raise exception 'Default sales units must be greater than zero.'; end if;
    if p_effective_from is null then raise exception 'Effective-from date is required.'; end if;
    v_reason:=nullif(btrim(coalesce(p_reason,'')),'');
    if v_reason is null then raise exception 'Reason is required.'; end if;
    v_ref:=nullif(btrim(coalesce(p_approval_reference,'')),'');
    perform pg_advisory_xact_lock(hashtextextended('PPM_REGIONAL_SALES_ALLOCATION_DEFAULT:'||v_scenario||':'||v_region,0));
    select * into v_previous from costing.regional_sales_allocation_default_policy p
      where p.scenario_code=v_scenario and p.region_code=v_region and p.status='APPROVED' and p.effective_to is null
      order by p.effective_from desc,p.id desc limit 1 for update;
    if found then
      if p_effective_from<=v_previous.effective_from then raise exception 'New policy effective date must be later than the current open policy effective date %.',v_previous.effective_from; end if;
      update costing.regional_sales_allocation_default_policy set effective_to=p_effective_from-1,status='CLOSED',closed_at=clock_timestamp(),closed_by=v_actor where id=v_previous.id;
    end if;
    insert into costing.regional_sales_allocation_default_policy(scenario_code,region_code,default_sales_units,effective_from,status,reason,approval_reference,previous_policy_id,created_at,created_by)
    values(v_scenario,v_region,p_default_sales_units,p_effective_from,'APPROVED',v_reason,v_ref,v_previous.id,clock_timestamp(),v_actor)
    returning * into v_saved;
    return query select v_saved.id,v_saved.scenario_code,v_saved.region_code,v_saved.default_sales_units,v_saved.effective_from,v_saved.effective_to,v_saved.status,v_saved.previous_policy_id,v_saved.created_at,v_saved.created_by;
end;
$function$;

grant execute on function public.rpc_get_regional_sales_allocation_default_policies()
  to anon, authenticated, service_role;
grant execute on function public.rpc_set_regional_sales_allocation_default_policy(text, text, numeric, date, text, text)
  to anon, authenticated, service_role;

insert into costing.regional_sales_allocation_default_policy (
  scenario_code,
  region_code,
  default_sales_units,
  effective_from,
  status,
  reason,
  approval_reference
) values
  (
    'NO_ELIGIBLE_REGIONAL_HISTORY',
    'IK',
    10,
    '2026-09-10',
    'APPROVED',
    'Initial governed regional allocation-volume default aligned with the established 10-unit new-SKU/new-product policy. Used only when higher-precedence regional actual evidence or explicit governed assumption cannot supply the required regional basis.',
    'GATE6C-SEP2026-REGIONAL-DEFAULT-10'
  ),
  (
    'NO_ELIGIBLE_REGIONAL_HISTORY',
    'OK',
    10,
    '2026-09-10',
    'APPROVED',
    'Initial governed regional allocation-volume default aligned with the established 10-unit new-SKU/new-product policy. Used only when higher-precedence regional actual evidence or explicit governed assumption cannot supply the required regional basis.',
    'GATE6C-SEP2026-REGIONAL-DEFAULT-10'
  ),
  (
    'NO_POSITIVE_REGIONAL_HISTORY',
    'IK',
    10,
    '2026-09-10',
    'APPROVED',
    'Initial governed regional allocation-volume default aligned with the established 10-unit new-SKU/new-product policy. Used only when higher-precedence regional actual evidence or explicit governed assumption cannot supply the required regional basis.',
    'GATE6C-SEP2026-REGIONAL-DEFAULT-10'
  ),
  (
    'NO_POSITIVE_REGIONAL_HISTORY',
    'OK',
    10,
    '2026-09-10',
    'APPROVED',
    'Initial governed regional allocation-volume default aligned with the established 10-unit new-SKU/new-product policy. Used only when higher-precedence regional actual evidence or explicit governed assumption cannot supply the required regional basis.',
    'GATE6C-SEP2026-REGIONAL-DEFAULT-10'
  );
