begin;

create or replace function regulatory.normalize_controlled_term_alias(p_text text)
returns text
language sql
immutable
strict
set search_path = ''
as $function$
  select lower(regexp_replace(btrim(p_text), '[[:space:]]+', ' ', 'g'));
$function$;

comment on function regulatory.normalize_controlled_term_alias(text) is
  'Conservative controlled-term alias normalizer: trim, collapse whitespace, lowercase; punctuation and diacritics are preserved.';

create table regulatory.controlled_term_alias (
  id bigint generated by default as identity primary key,
  domain_code text not null,
  controlled_term_id bigint not null,
  alias_text text not null,
  alias_key text generated always as (regulatory.normalize_controlled_term_alias(alias_text)) stored,
  mapping_status text not null,
  match_basis text,
  comparison_evidence jsonb not null default '{}'::jsonb,
  mapping_reason text,
  effective_from timestamptz,
  effective_to timestamptz,
  verified_by uuid,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  constraint controlled_term_alias_domain_fk
    foreign key (controlled_term_id, domain_code)
    references regulatory.controlled_term(id, domain_code)
    on delete restrict,
  constraint controlled_term_alias_status_check
    check (mapping_status in ('DRAFT','VERIFIED','REJECTED','SUPERSEDED')),
  constraint controlled_term_alias_text_nonblank check (btrim(alias_text) <> ''),
  constraint controlled_term_alias_key_nonblank check (btrim(alias_key) <> ''),
  constraint controlled_term_alias_window_check
    check (effective_to is null or effective_from is null or effective_to > effective_from),
  constraint controlled_term_alias_verification_check
    check (
      (mapping_status = 'VERIFIED' and verified_by is not null and verified_at is not null)
      or
      (mapping_status <> 'VERIFIED' and verified_by is null and verified_at is null)
    )
);

comment on table regulatory.controlled_term_alias is
  'Global governed mapping from observed source wording to a canonical controlled term. Product and line identity do not participate in alias authority.';

create unique index uq_controlled_term_alias_current
  on regulatory.controlled_term_alias(domain_code, alias_key)
  where mapping_status in ('DRAFT','VERIFIED');

create index ix_controlled_term_alias_domain_key
  on regulatory.controlled_term_alias(domain_code, alias_key);

create index ix_controlled_term_alias_term_status
  on regulatory.controlled_term_alias(controlled_term_id, mapping_status);

create index ix_controlled_term_alias_key_trgm
  on regulatory.controlled_term_alias using gin (alias_key extensions.gin_trgm_ops);

create unique index uq_reference_work_active_normalized_label
  on regulatory.controlled_term (
    regulatory.normalize_controlled_term_alias(label)
  )
  where domain_code='REFERENCE_WORK' and is_active=true;

alter table regulatory.controlled_term_alias enable row level security;

revoke all on table regulatory.controlled_term_alias from public, anon, authenticated;
grant select, insert, update, delete on table regulatory.controlled_term_alias to service_role;

create trigger controlled_term_alias_set_audit_cols
before insert or update on regulatory.controlled_term_alias
for each row execute function public.set_audit_cols();

create trigger controlled_term_alias_audit
after insert or update or delete on regulatory.controlled_term_alias
for each row execute function regulatory.trg_audit_row();

comment on column regulatory.eaushadhi_line_review.suggested_reference_work_term_id is
  'Deprecated compatibility field. Non-authoritative for Reference execution/readiness; global controlled_term_alias resolution is authoritative.';
comment on column regulatory.eaushadhi_line_review.selected_reference_work_term_id is
  'Deprecated compatibility field. Non-authoritative for Reference execution/readiness; global controlled_term_alias resolution is authoritative.';

create or replace function public.rpc_eaushadhi_reference_work_options()
returns table(
  controlled_term_id bigint,
  code text,
  label text
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  perform public.rpc_eaushadhi_require_permission(false);
  return query
  select ct.id, ct.code, ct.label
  from regulatory.controlled_term ct
  where ct.domain_code='REFERENCE_WORK'
    and ct.is_active=true
  order by lower(ct.label), ct.id;
end
$function$;

create or replace function public.rpc_eaushadhi_reference_alias_candidates(
  p_source_reference_text text
)
returns table(
  canonical_term_id bigint,
  canonical_code text,
  canonical_label text,
  match_basis text,
  similarity_score double precision,
  comparison_evidence jsonb,
  candidate_rank integer
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_source text := nullif(btrim(coalesce(p_source_reference_text,'')), '');
  v_source_norm text;
  v_parent text;
  v_parent_norm text;
begin
  perform public.rpc_eaushadhi_require_permission(false);
  if v_source is null then
    raise exception 'Source reference text is required' using errcode='22023';
  end if;

  v_source_norm := regulatory.normalize_controlled_term_alias(v_source);
  v_parent := case
    when position(' - ' in v_source) > 0 then btrim(split_part(v_source,' - ',1))
    else null
  end;
  v_parent_norm := case when v_parent is not null
    then regulatory.normalize_controlled_term_alias(v_parent)
    else null
  end;

  return query
  with ranked as (
    select
      ct.id,
      ct.code,
      ct.label,
      case
        when v_source=ct.label then 'EXACT'
        when v_source_norm=regulatory.normalize_controlled_term_alias(ct.label) then 'NORMALIZED_EXACT'
        when v_parent_norm is not null
          and v_parent_norm=regulatory.normalize_controlled_term_alias(ct.label)
          then 'PARENT_WORK_MATCH'
        else 'FUZZY_CANDIDATE'
      end as basis,
      extensions.similarity(
        v_source_norm,
        regulatory.normalize_controlled_term_alias(ct.label)
      )::double precision as sim,
      jsonb_build_object(
        'source_text', v_source,
        'normalized_source', v_source_norm,
        'extracted_parent', v_parent,
        'normalized_parent', v_parent_norm,
        'canonical_text', ct.label,
        'normalized_canonical', regulatory.normalize_controlled_term_alias(ct.label),
        'similarity_score', extensions.similarity(
          v_source_norm,
          regulatory.normalize_controlled_term_alias(ct.label)
        )
      ) as evidence,
      case
        when v_source=ct.label then 1
        when v_source_norm=regulatory.normalize_controlled_term_alias(ct.label) then 2
        when v_parent_norm is not null
          and v_parent_norm=regulatory.normalize_controlled_term_alias(ct.label)
          then 3
        else 4
      end as class_rank
    from regulatory.controlled_term ct
    where ct.domain_code='REFERENCE_WORK'
      and ct.is_active=true
  ),
  ordered as (
    select *,
      row_number() over(order by class_rank, sim desc, code, id)::integer as rn
    from ranked
  )
  select id, code, label, basis, sim, evidence, rn
  from ordered
  where rn <= 10
  order by rn;
end
$function$;

create or replace function public.rpc_eaushadhi_reference_alias_draft_create(
  p_source_reference_text text,
  p_controlled_term_id bigint
)
returns table(
  alias_mapping_id bigint,
  mapping_status text,
  source_reference_text text,
  alias_key text,
  canonical_term_id bigint,
  canonical_code text,
  canonical_label text,
  match_basis text,
  comparison_evidence jsonb
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor uuid;
  v_source text := nullif(btrim(coalesce(p_source_reference_text,'')), '');
  v_alias_key text;
  v_parent text;
  v_parent_norm text;
  v_term regulatory.controlled_term%rowtype;
  v_basis text;
  v_similarity double precision;
  v_line_count bigint;
  v_product_count bigint;
  v_id bigint;
  v_evidence jsonb;
begin
  v_actor := public.rpc_eaushadhi_require_permission(true);
  if v_source is null then
    raise exception 'Source reference text is required' using errcode='22023';
  end if;

  if not exists (
    select 1
    from regulatory.source_composition_line scl
    where scl.raw_reference_text=v_source
  ) then
    raise exception 'Source reference text is not present in governed source composition data'
      using errcode='22023';
  end if;

  select * into strict v_term
  from regulatory.controlled_term ct
  where ct.id=p_controlled_term_id
    and ct.domain_code='REFERENCE_WORK'
    and ct.is_active=true;

  v_alias_key := regulatory.normalize_controlled_term_alias(v_source);

  if exists (
    select 1
    from regulatory.controlled_term_alias a
    where a.domain_code='REFERENCE_WORK'
      and a.alias_key=v_alias_key
      and a.mapping_status in ('DRAFT','VERIFIED')
  ) then
    raise exception 'A current alias mapping already exists for this source reference'
      using errcode='23505';
  end if;

  select count(*),
         count(distinct scl.matched_product_id)
           filter (where scl.matched_product_id is not null)
  into v_line_count, v_product_count
  from regulatory.source_composition_line scl
  where scl.raw_reference_text=v_source;

  v_parent := case
    when position(' - ' in v_source) > 0 then btrim(split_part(v_source,' - ',1))
    else null
  end;
  v_parent_norm := case when v_parent is not null
    then regulatory.normalize_controlled_term_alias(v_parent)
    else null
  end;

  v_similarity := extensions.similarity(
    v_alias_key,
    regulatory.normalize_controlled_term_alias(v_term.label)
  );

  v_basis := case
    when v_source=v_term.label then 'EXACT'
    when v_alias_key=regulatory.normalize_controlled_term_alias(v_term.label)
      then 'NORMALIZED_EXACT'
    when v_parent_norm is not null
      and v_parent_norm=regulatory.normalize_controlled_term_alias(v_term.label)
      then 'PARENT_WORK_MATCH'
    else 'FUZZY_CANDIDATE'
  end;

  v_evidence := jsonb_build_object(
    'source_text', v_source,
    'normalized_source', v_alias_key,
    'extracted_parent', v_parent,
    'normalized_parent', v_parent_norm,
    'canonical_term_id', v_term.id,
    'canonical_code', v_term.code,
    'canonical_label', v_term.label,
    'normalized_canonical', regulatory.normalize_controlled_term_alias(v_term.label),
    'similarity_score', v_similarity,
    'line_count', v_line_count,
    'product_count', v_product_count
  );

  insert into regulatory.controlled_term_alias(
    domain_code, controlled_term_id, alias_text, mapping_status,
    match_basis, comparison_evidence, mapping_reason,
    created_by, updated_by
  ) values (
    'REFERENCE_WORK', v_term.id, v_source, 'DRAFT',
    v_basis, v_evidence,
    'Global source-reference candidate for canonical REFERENCE_WORK governance.',
    v_actor, v_actor
  )
  returning id into v_id;

  return query
  select v_id, 'DRAFT'::text, v_source, v_alias_key,
         v_term.id, v_term.code, v_term.label, v_basis, v_evidence;
end
$function$;

create or replace function public.rpc_eaushadhi_reference_alias_verify(
  p_alias_mapping_id bigint,
  p_expected_status text,
  p_controlled_term_id bigint
)
returns table(
  alias_mapping_id bigint,
  mapping_status text,
  canonical_term_id bigint,
  canonical_code text,
  canonical_label text,
  match_basis text,
  verified_by uuid,
  verified_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor uuid;
  v_alias regulatory.controlled_term_alias%rowtype;
  v_original_term regulatory.controlled_term%rowtype;
  v_selected_term regulatory.controlled_term%rowtype;
  v_now timestamptz := now();
  v_basis text;
  v_evidence jsonb;
begin
  v_actor := public.rpc_eaushadhi_require_permission(true);

  select * into strict v_alias
  from regulatory.controlled_term_alias
  where id=p_alias_mapping_id
  for update;

  if v_alias.mapping_status is distinct from upper(btrim(coalesce(p_expected_status,''))) then
    raise exception 'Reference alias state changed; reload before verifying'
      using errcode='40001';
  end if;

  if v_alias.mapping_status <> 'DRAFT' then
    raise exception 'Only a DRAFT reference alias may transition to VERIFIED'
      using errcode='22023';
  end if;

  if (v_alias.effective_from is not null and v_alias.effective_from > v_now)
     or (v_alias.effective_to is not null and v_alias.effective_to <= v_now) then
    raise exception 'Reference alias is not currently effective'
      using errcode='22023';
  end if;

  select * into strict v_original_term
  from regulatory.controlled_term
  where id=v_alias.controlled_term_id
    and domain_code='REFERENCE_WORK'
    and is_active=true;

  select * into strict v_selected_term
  from regulatory.controlled_term
  where id=p_controlled_term_id
    and domain_code='REFERENCE_WORK'
    and is_active=true;

  if v_selected_term.id=v_original_term.id then
    v_basis := v_alias.match_basis;
    v_evidence := v_alias.comparison_evidence;
  else
    v_basis := 'MANUAL';
    v_evidence := coalesce(v_alias.comparison_evidence,'{}'::jsonb)
      || jsonb_build_object(
        'original_suggested_term_id', v_original_term.id,
        'original_suggested_code', v_original_term.code,
        'original_suggested_label', v_original_term.label,
        'verified_term_id', v_selected_term.id,
        'verified_code', v_selected_term.code,
        'verified_label', v_selected_term.label,
        'verification_mode', 'MANUAL_SELECTION'
      );
  end if;

  update regulatory.controlled_term_alias a
  set controlled_term_id=v_selected_term.id,
      mapping_status='VERIFIED',
      match_basis=v_basis,
      comparison_evidence=v_evidence,
      verified_by=v_actor,
      verified_at=v_now,
      updated_by=v_actor
  where a.id=v_alias.id;

  return query
  select v_alias.id, 'VERIFIED'::text,
         v_selected_term.id, v_selected_term.code, v_selected_term.label,
         v_basis, v_actor, v_now;
end
$function$;

create or replace function public.rpc_eaushadhi_reference_work_create(p_label text)
returns table(
  controlled_term_id bigint,
  code text,
  label text
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor uuid;
  v_label text := nullif(btrim(coalesce(p_label,'')), '');
  v_norm text;
  v_id bigint;
  v_code text;
begin
  v_actor := public.rpc_eaushadhi_require_permission(true);
  if v_label is null then
    raise exception 'Reference work label is required' using errcode='22023';
  end if;

  v_norm := regulatory.normalize_controlled_term_alias(v_label);

  if exists (
    select 1
    from regulatory.controlled_term ct
    where ct.domain_code='REFERENCE_WORK'
      and ct.is_active=true
      and regulatory.normalize_controlled_term_alias(ct.label)=v_norm
  ) then
    raise exception 'An active canonical Reference Work already exists with this normalized label'
      using errcode='23505';
  end if;

  select nextval('regulatory.controlled_term_id_seq'::regclass) into v_id;
  v_code := 'REFERENCE_WORK_' || lpad(v_id::text,6,'0');

  insert into regulatory.controlled_term(
    id, domain_code, code, label, description,
    is_active, created_by, updated_by
  )
  overriding system value
  values (
    v_id, 'REFERENCE_WORK', v_code, v_label,
    'Canonical Reference Work created through global e-Aushadhi Reference Dictionary governance.',
    true, v_actor, v_actor
  );

  return query select v_id, v_code, v_label;
end
$function$;

create or replace function public.rpc_eaushadhi_reference_dictionary_get()
returns table(
  source_reference_text text,
  line_count bigint,
  product_count bigint,
  alias_mapping_id bigint,
  alias_mapping_status text,
  alias_match_basis text,
  alias_mapping_reason text,
  alias_comparison_evidence jsonb,
  canonical_term_id bigint,
  canonical_code text,
  canonical_label text,
  portal_mapping_id bigint,
  portal_mapping_status text,
  portal_option_id bigint,
  portal_external_id text,
  portal_label text,
  source_to_canonical_ready boolean,
  canonical_to_portal_ready boolean,
  reference_ready boolean
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  perform public.rpc_eaushadhi_require_permission(false);

  return query
  with refs as (
    select
      scl.raw_reference_text as source_text,
      count(*)::bigint as line_count,
      count(distinct scl.matched_product_id)
        filter (where scl.matched_product_id is not null)::bigint as product_count
    from regulatory.source_composition_line scl
    where nullif(btrim(scl.raw_reference_text),'') is not null
    group by scl.raw_reference_text
  )
  select
    r.source_text,
    r.line_count,
    r.product_count,
    a.id,
    a.mapping_status,
    a.match_basis,
    a.mapping_reason,
    a.comparison_evidence,
    ct.id,
    ct.code,
    ct.label,
    pm.id,
    pm.mapping_status,
    po.id,
    po.external_id,
    po.label,
    (
      a.mapping_status='VERIFIED'
      and (a.effective_from is null or a.effective_from <= now())
      and (a.effective_to is null or a.effective_to > now())
      and ct.id is not null and ct.is_active=true
    ),
    (
      a.mapping_status='VERIFIED'
      and (a.effective_from is null or a.effective_from <= now())
      and (a.effective_to is null or a.effective_to > now())
      and ct.id is not null and ct.is_active=true
      and pm.mapping_status='VERIFIED'
      and (pm.effective_from is null or pm.effective_from <= now())
      and (pm.effective_to is null or pm.effective_to > now())
      and po.id is not null and po.is_active=true
      and po.portal_code='E_AUSHADHI'
      and po.domain_code='REFERENCE'
      and po.external_id <> '-1'
    ),
    (
      a.mapping_status='VERIFIED'
      and (a.effective_from is null or a.effective_from <= now())
      and (a.effective_to is null or a.effective_to > now())
      and ct.id is not null and ct.is_active=true
      and pm.mapping_status='VERIFIED'
      and (pm.effective_from is null or pm.effective_from <= now())
      and (pm.effective_to is null or pm.effective_to > now())
      and po.id is not null and po.is_active=true
      and po.portal_code='E_AUSHADHI'
      and po.domain_code='REFERENCE'
      and po.external_id <> '-1'
    )
  from refs r
  left join lateral (
    select ca.*
    from regulatory.controlled_term_alias ca
    where ca.domain_code='REFERENCE_WORK'
      and ca.alias_key=regulatory.normalize_controlled_term_alias(r.source_text)
      and ca.mapping_status in ('DRAFT','VERIFIED')
      and (ca.effective_from is null or ca.effective_from <= now())
      and (ca.effective_to is null or ca.effective_to > now())
    order by (ca.mapping_status='VERIFIED') desc, ca.id desc
    limit 1
  ) a on true
  left join regulatory.controlled_term ct
    on ct.id=a.controlled_term_id
   and ct.domain_code='REFERENCE_WORK'
  left join lateral (
    select m.*
    from regulatory.term_portal_mapping m
    where m.controlled_term_id=ct.id
      and m.portal_code='E_AUSHADHI'
      and m.mapping_status in ('DRAFT','VERIFIED')
      and (m.effective_from is null or m.effective_from <= now())
      and (m.effective_to is null or m.effective_to > now())
    order by (m.mapping_status='VERIFIED') desc, m.id desc
    limit 1
  ) pm on true
  left join regulatory.portal_option po on po.id=pm.portal_option_id
  order by lower(r.source_text), r.source_text;
end
$function$;

do $seed$
declare
  v_term_id bigint;
  v_source text;
  v_alias_key text;
  v_line_count bigint;
  v_product_count bigint;
begin
  select ct.id into strict v_term_id
  from regulatory.controlled_term ct
  where ct.domain_code='REFERENCE_WORK'
    and ct.code='SAHASRAYOGAM'
    and ct.is_active=true;

  foreach v_source in array array[
    'Sahasrayōgam - Sujanapriya',
    'Sahasrayōgam - Vaidyapriya'
  ]
  loop
    v_alias_key := regulatory.normalize_controlled_term_alias(v_source);
    if not exists (
      select 1
      from regulatory.controlled_term_alias a
      where a.domain_code='REFERENCE_WORK'
        and a.alias_key=v_alias_key
        and a.mapping_status in ('DRAFT','VERIFIED')
    ) then
      select count(*),
             count(distinct scl.matched_product_id)
               filter (where scl.matched_product_id is not null)
      into v_line_count, v_product_count
      from regulatory.source_composition_line scl
      where scl.raw_reference_text=v_source;

      if v_line_count > 0 then
        insert into regulatory.controlled_term_alias(
          domain_code, controlled_term_id, alias_text, mapping_status,
          match_basis, comparison_evidence, mapping_reason
        ) values (
          'REFERENCE_WORK', v_term_id, v_source, 'DRAFT',
          'PARENT_WORK_MATCH',
          jsonb_build_object(
            'source_text', v_source,
            'normalized_source', v_alias_key,
            'extracted_parent', split_part(v_source,' - ',1),
            'normalized_parent', regulatory.normalize_controlled_term_alias(split_part(v_source,' - ',1)),
            'canonical_text', 'Sahasrayōgam',
            'normalized_canonical', regulatory.normalize_controlled_term_alias('Sahasrayōgam'),
            'line_count', v_line_count,
            'product_count', v_product_count
          ),
          'Deterministic global parent-work candidate; source subsection remains preserved in raw source text.'
        );
      end if;
    end if;
  end loop;
end
$seed$;

revoke all on function regulatory.normalize_controlled_term_alias(text) from public, anon, authenticated;
grant execute on function regulatory.normalize_controlled_term_alias(text) to service_role;

revoke all on function public.rpc_eaushadhi_reference_work_options() from public, anon;
grant execute on function public.rpc_eaushadhi_reference_work_options() to authenticated, service_role;

revoke all on function public.rpc_eaushadhi_reference_alias_candidates(text) from public, anon;
grant execute on function public.rpc_eaushadhi_reference_alias_candidates(text) to authenticated, service_role;

revoke all on function public.rpc_eaushadhi_reference_alias_draft_create(text,bigint) from public, anon;
grant execute on function public.rpc_eaushadhi_reference_alias_draft_create(text,bigint) to authenticated, service_role;

revoke all on function public.rpc_eaushadhi_reference_alias_verify(bigint,text,bigint) from public, anon;
grant execute on function public.rpc_eaushadhi_reference_alias_verify(bigint,text,bigint) to authenticated, service_role;

revoke all on function public.rpc_eaushadhi_reference_work_create(text) from public, anon;
grant execute on function public.rpc_eaushadhi_reference_work_create(text) to authenticated, service_role;

revoke all on function public.rpc_eaushadhi_reference_dictionary_get() from public, anon;
grant execute on function public.rpc_eaushadhi_reference_dictionary_get() to authenticated, service_role;

alter function regulatory.normalize_controlled_term_alias(text) owner to postgres;
alter function public.rpc_eaushadhi_reference_work_options() owner to postgres;
alter function public.rpc_eaushadhi_reference_alias_candidates(text) owner to postgres;
alter function public.rpc_eaushadhi_reference_alias_draft_create(text,bigint) owner to postgres;
alter function public.rpc_eaushadhi_reference_alias_verify(bigint,text,bigint) owner to postgres;
alter function public.rpc_eaushadhi_reference_work_create(text) owner to postgres;
alter function public.rpc_eaushadhi_reference_dictionary_get() owner to postgres;

commit;
