
insert into regulatory.controlled_term (domain_code,code,label,description,is_active)
select 'QC_PROTOCOL','NOT_APPLICABLE','N/A','e-Aushadhi QC protocol explicit not-applicable choice',true
where not exists (
  select 1 from regulatory.controlled_term
  where domain_code='QC_PROTOCOL' and code='NOT_APPLICABLE'
);

alter table regulatory.stability_study
  add column if not exists other_testing_protocol_text text null;

create or replace function regulatory.trg_validate_stability_study_qc_contract()
returns trigger
language plpgsql
set search_path to 'regulatory','public','pg_temp'
as $$
declare
  v_code text;
  v_domain text;
begin
  select domain_code,code into v_domain,v_code
  from regulatory.controlled_term
  where id=new.testing_protocol_term_id;

  if v_domain is distinct from 'QC_PROTOCOL' then
    raise exception using errcode='23514', message='stability_study testing protocol must belong to QC_PROTOCOL';
  end if;

  if v_code='OTHER' then
    if nullif(btrim(coalesce(new.other_testing_protocol_text,'')),'') is null then
      raise exception using errcode='23514', message='Other Testing Protocol text is required when QC protocol is OTHER';
    end if;
  elsif new.other_testing_protocol_text is not null then
    raise exception using errcode='23514', message='Other Testing Protocol text must be null unless QC protocol is OTHER';
  end if;

  return new;
end
$$;

drop trigger if exists trg_validate_stability_study_qc_contract on regulatory.stability_study;
create trigger trg_validate_stability_study_qc_contract
before insert or update of testing_protocol_term_id,other_testing_protocol_text
on regulatory.stability_study
for each row execute function regulatory.trg_validate_stability_study_qc_contract();

insert into regulatory.portal_option
(portal_code,domain_code,external_id,label,source_context,is_active,parent_domain_code,parent_external_id,notes)
select v.portal_code,v.domain_code,v.external_id,v.label,v.source_context,true,'','',v.notes
from (values
 ('E_AUSHADHI','QC_PROTOCOL','3 Month Accelarated Stability','(3) Month Accelarated Stability',
  '{"capture_id":"6b96ce22-a7be-4d5a-82b3-e46b9e752ea4","captured_at":"2026-10-04T14:45:45.308Z","route":"/admin/addQCRegister"}'::jsonb,
  'WP-07 G0A read-only portal capture'),
 ('E_AUSHADHI','QC_PROTOCOL','6 Month Accelarated Stability','(6) Month Accelarated Stability',
  '{"capture_id":"6b96ce22-a7be-4d5a-82b3-e46b9e752ea4","captured_at":"2026-10-04T14:45:45.308Z","route":"/admin/addQCRegister"}'::jsonb,
  'WP-07 G0A read-only portal capture'),
 ('E_AUSHADHI','QC_PROTOCOL','Real Time Stability','Real Time Stability',
  '{"capture_id":"6b96ce22-a7be-4d5a-82b3-e46b9e752ea4","captured_at":"2026-10-04T14:45:45.308Z","route":"/admin/addQCRegister"}'::jsonb,
  'WP-07 G0A read-only portal capture'),
 ('E_AUSHADHI','QC_PROTOCOL','Others','Others',
  '{"capture_id":"6b96ce22-a7be-4d5a-82b3-e46b9e752ea4","captured_at":"2026-10-04T14:45:45.308Z","route":"/admin/addQCRegister"}'::jsonb,
  'WP-07 G0A read-only portal capture'),
 ('E_AUSHADHI','QC_PROTOCOL','N/A','N/A',
  '{"capture_id":"6b96ce22-a7be-4d5a-82b3-e46b9e752ea4","captured_at":"2026-10-04T14:45:45.308Z","route":"/admin/addQCRegister"}'::jsonb,
  'WP-07 G0A read-only portal capture')
) as v(portal_code,domain_code,external_id,label,source_context,notes)
where not exists (
  select 1 from regulatory.portal_option p
  where p.portal_code=v.portal_code
    and p.domain_code=v.domain_code
    and p.external_id=v.external_id
    and p.parent_domain_code=''
    and p.parent_external_id=''
);

insert into regulatory.term_portal_mapping
(controlled_term_id,portal_code,portal_option_id,mapping_status,mapping_reason,comparison_evidence,match_basis)
select ct.id,'E_AUSHADHI',po.id,'DRAFT',
       'WP-07 G0A exact portal option captured; human/governed verification remains required',
       jsonb_build_object('capture_id','6b96ce22-a7be-4d5a-82b3-e46b9e752ea4','portal_label',po.label,'portal_external_id',po.external_id),
       'EXACT_CAPTURE'
from regulatory.controlled_term ct
join regulatory.portal_option po
  on po.portal_code='E_AUSHADHI'
 and po.domain_code='QC_PROTOCOL'
 and po.parent_domain_code=''
 and po.parent_external_id=''
 and (
   (ct.code='ACCELERATED_3_MONTH' and po.external_id='3 Month Accelarated Stability')
   or (ct.code='ACCELERATED_6_MONTH' and po.external_id='6 Month Accelarated Stability')
   or (ct.code='REAL_TIME_STABILITY' and po.external_id='Real Time Stability')
   or (ct.code='OTHER' and po.external_id='Others')
   or (ct.code='NOT_APPLICABLE' and po.external_id='N/A')
 )
where ct.domain_code='QC_PROTOCOL'
and not exists (
  select 1 from regulatory.term_portal_mapping m
  where m.controlled_term_id=ct.id and m.portal_option_id=po.id
);

create table if not exists regulatory.eaushadhi_qc_laboratory_mapping (
  id bigint generated by default as identity primary key,
  approved_laboratory_id bigint not null references regulatory.approved_laboratory(id) on delete restrict,
  portal_external_id text not null check (btrim(portal_external_id)<>''),
  portal_label text not null check (btrim(portal_label)<>''),
  mapping_status text not null default 'DRAFT'
    check (mapping_status in ('DRAFT','VERIFIED','REJECTED','SUPERSEDED')),
  comparison_evidence jsonb not null default '{}'::jsonb,
  verified_by uuid null,
  verified_at timestamptz null,
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_by uuid null,
  updated_at timestamptz not null default now(),
  check (mapping_status <> 'VERIFIED' or (verified_by is not null and verified_at is not null))
);
create unique index if not exists eaushadhi_qc_laboratory_mapping_verified_uidx
  on regulatory.eaushadhi_qc_laboratory_mapping(approved_laboratory_id)
  where mapping_status='VERIFIED';

create table if not exists regulatory.eaushadhi_qc_stage (
  product_id integer primary key references regulatory.eaushadhi_product_workflow(product_id) on delete cascade,
  stage_status text not null default 'NOT_STARTED'
    check (stage_status in ('NOT_STARTED','PARTIAL','PORTAL_VERIFIED')),
  row_version bigint not null default 1 check (row_version>0),
  content_hash text null check (content_hash is null or content_hash ~ '^[0-9a-f]{64}$'),
  workflow_row_version bigint null check (workflow_row_version is null or workflow_row_version>0),
  composition_stage_row_version bigint null check (composition_stage_row_version is null or composition_stage_row_version>0),
  governed_record_count integer not null default 0 check (governed_record_count>=0),
  portal_match_count integer not null default 0 check (portal_match_count>=0),
  latest_evidence jsonb not null default '{}'::jsonb,
  portal_verified_by uuid null,
  portal_verified_at timestamptz null,
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_by uuid null,
  updated_at timestamptz not null default now(),
  check (portal_match_count<=governed_record_count)
);

create table if not exists regulatory.eaushadhi_qc_run (
  run_id uuid primary key default gen_random_uuid(),
  product_id integer not null references regulatory.eaushadhi_product_workflow(product_id) on delete cascade,
  target_stability_study_id bigint not null references regulatory.stability_study(id) on delete restrict,
  run_status text not null
    check (run_status in ('SAVE_ARMED','SAVE_CONFIRMED','SAVE_AMBIGUOUS','SAVE_REJECTED','ROW_VERIFIED')),
  start_stage_row_version bigint not null check (start_stage_row_version>0),
  current_stage_row_version bigint not null check (current_stage_row_version>0),
  workflow_row_version bigint not null check (workflow_row_version>0),
  composition_stage_row_version bigint not null check (composition_stage_row_version>0),
  content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
  portal_product_ref text not null check (btrim(portal_product_ref)<>''),
  page_identity_evidence jsonb not null,
  before_list_evidence jsonb not null,
  planner_report jsonb not null,
  target_projection jsonb not null,
  save_outcome text null check (save_outcome is null or save_outcome in ('CONFIRMED','AMBIGUOUS','REJECTED')),
  save_evidence jsonb null,
  after_list_evidence jsonb null,
  reread_evidence jsonb null,
  document_reread_evidence jsonb null,
  verify_report jsonb null,
  resolved_portal_row_id text null,
  armed_by uuid not null,
  armed_at timestamptz not null default now(),
  save_recorded_by uuid null,
  save_recorded_at timestamptz null,
  row_verified_by uuid null,
  row_verified_at timestamptz null,
  updated_at timestamptz not null default now()
);
create unique index if not exists eaushadhi_qc_run_active_product_uidx
  on regulatory.eaushadhi_qc_run(product_id)
  where run_status in ('SAVE_ARMED','SAVE_CONFIRMED','SAVE_AMBIGUOUS');
create index if not exists eaushadhi_qc_run_product_started_idx
  on regulatory.eaushadhi_qc_run(product_id,armed_at desc);

revoke all on regulatory.eaushadhi_qc_laboratory_mapping from public,anon,authenticated;
revoke all on regulatory.eaushadhi_qc_stage from public,anon,authenticated;
revoke all on regulatory.eaushadhi_qc_run from public,anon,authenticated;

create or replace function regulatory.eaushadhi_qc_snapshot_v1(
  p_product_id integer,
  p_expected_workflow_row_version bigint
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','regulatory','extensions','pg_temp'
as $$
declare
  v_workflow regulatory.eaushadhi_product_workflow%rowtype;
  v_comp regulatory.eaushadhi_composition_stage%rowtype;
  v_records jsonb := '[]'::jsonb;
  v_record jsonb;
  v_reasons text[] := array[]::text[];
  v_ids jsonb := '[]'::jsonb;
  v_count integer := 0;
  v_hash text;
begin
  if p_product_id is null or p_product_id<=0 then
    raise exception using errcode='22023',message='Product ID must be positive';
  end if;
  if p_expected_workflow_row_version is null or p_expected_workflow_row_version<=0 then
    raise exception using errcode='22023',message='Expected workflow row version must be positive';
  end if;

  select * into v_workflow from regulatory.eaushadhi_product_workflow where product_id=p_product_id;
  if not found then
    raise exception using errcode='P0002',message='e-Aushadhi product workflow not found';
  end if;
  if v_workflow.row_version is distinct from p_expected_workflow_row_version then
    raise exception using errcode='40001',message='Stale workflow row version';
  end if;
  if v_workflow.entry_status is distinct from 'PORTAL_VERIFIED' then
    v_reasons:=array_append(v_reasons,'PRODUCT_DETAILS_NOT_PORTAL_VERIFIED');
  end if;
  if nullif(btrim(coalesce(v_workflow.portal_product_ref,'')),'') is null then
    v_reasons:=array_append(v_reasons,'PORTAL_PRODUCT_REF_MISSING');
  end if;

  select * into v_comp from regulatory.eaushadhi_composition_stage where product_id=p_product_id;
  if not found or v_comp.stage_status is distinct from 'PORTAL_VERIFIED' then
    v_reasons:=array_append(v_reasons,'COMPOSITION_NOT_PORTAL_VERIFIED');
  end if;

  for v_record in
    select jsonb_build_object(
      'stability_study_id',s.id,
      'product_id',s.product_id,
      'protocol',jsonb_build_object(
        'controlled_term_id',ct.id,'code',ct.code,'label',ct.label,
        'mapping_status',coalesce(pm.mapping_status,'MISSING'),
        'portal_option_id',po.id,'portal_external_id',po.external_id,'portal_label',po.label
      ),
      'other_testing_protocol_text',s.other_testing_protocol_text,
      'study_start_date',s.study_start_date,
      'study_end_date',s.study_end_date,
      'shelf_life_months',s.shelf_life_months,
      'batch_numbers',coalesce(b.batches,'[]'::jsonb),
      'portal_batch_text',s.portal_batch_text,
      'report_date',s.report_date,
      'quality_control_mode',s.quality_control_mode,
      'approved_laboratory_id',s.approved_laboratory_id,
      'laboratory_mapping',case when s.quality_control_mode='OUT' then
        jsonb_build_object('mapping_status',coalesce(lm.mapping_status,'MISSING'),'portal_external_id',lm.portal_external_id,'portal_label',lm.portal_label)
        else null end,
      'document',case when d.document_count=1 then d.document_payload else null end,
      'document_count',coalesce(d.document_count,0),
      'source_status',s.status
    )
    from regulatory.stability_study s
    join regulatory.controlled_term ct on ct.id=s.testing_protocol_term_id
    left join lateral (
      select m.mapping_status,m.portal_option_id
      from regulatory.term_portal_mapping m
      where m.controlled_term_id=ct.id and m.portal_code='E_AUSHADHI'
        and m.mapping_status='VERIFIED'
        and (m.effective_from is null or m.effective_from<=current_date)
        and (m.effective_to is null or m.effective_to>=current_date)
      order by m.verified_at desc nulls last,m.id desc limit 1
    ) pm on true
    left join regulatory.portal_option po on po.id=pm.portal_option_id and po.portal_code='E_AUSHADHI'
      and po.domain_code='QC_PROTOCOL' and po.is_active=true
    left join lateral (
      select jsonb_agg(jsonb_build_object('sequence_no',sb.sequence_no,'bmr_id',sb.bmr_id,'batch_no',sb.batch_no) order by sb.sequence_no) batches
      from regulatory.stability_study_batch sb where sb.study_id=s.id
    ) b on true
    left join lateral (
      select count(*)::integer document_count,
             case when count(*)=1 then max(jsonb_build_object(
               'document_asset_id',da.id,'document_purpose',sd.document_purpose,'storage_bucket',da.storage_bucket,
               'storage_path',da.storage_path,'original_file_name',da.original_file_name,'mime_type',da.mime_type,
               'content_sha256',da.content_sha256,'generation_status',da.generation_status,'is_active',da.is_active
             )) else null end document_payload
      from regulatory.stability_study_document sd
      join regulatory.document_asset da on da.id=sd.document_asset_id
      where sd.study_id=s.id and sd.is_current=true and da.is_active=true
        and sd.document_purpose in ('TEST_REPORT','PORTAL_UPLOAD_ARTIFACT')
    ) d on true
    left join lateral (
      select m.mapping_status,m.portal_external_id,m.portal_label
      from regulatory.eaushadhi_qc_laboratory_mapping m
      where m.approved_laboratory_id=s.approved_laboratory_id and m.mapping_status='VERIFIED'
      order by m.verified_at desc nulls last,m.id desc limit 1
    ) lm on true
    where s.product_id=p_product_id and s.status in ('VERIFIED','READY','PORTAL_ENTERED')
    order by s.id
  loop
    v_count:=v_count+1;
    v_ids:=v_ids||jsonb_build_array((v_record->>'stability_study_id')::bigint);

    if coalesce(v_record#>>'{protocol,mapping_status}','')<>'VERIFIED'
       or nullif(v_record#>>'{protocol,portal_external_id}','') is null then
      v_reasons:=array_append(v_reasons,format('STUDY_%s_PROTOCOL_MAPPING_NOT_VERIFIED',v_record->>'stability_study_id'));
    end if;
    if coalesce(v_record#>>'{protocol,code}','')='OTHER'
       and nullif(btrim(coalesce(v_record->>'other_testing_protocol_text','')),'') is null then
      v_reasons:=array_append(v_reasons,format('STUDY_%s_OTHER_PROTOCOL_TEXT_MISSING',v_record->>'stability_study_id'));
    end if;
    if jsonb_array_length(coalesce(v_record->'batch_numbers','[]'::jsonb))=0
       and nullif(btrim(coalesce(v_record->>'portal_batch_text','')),'') is null then
      v_reasons:=array_append(v_reasons,format('STUDY_%s_BATCH_MISSING',v_record->>'stability_study_id'));
    end if;
    if coalesce((v_record->>'document_count')::integer,0)<>1
       or nullif(v_record#>>'{document,content_sha256}','') is null then
      v_reasons:=array_append(v_reasons,format('STUDY_%s_TEST_REPORT_NOT_FROZEN',v_record->>'stability_study_id'));
    end if;
    if coalesce(v_record->>'quality_control_mode','')='OUT'
       and coalesce(v_record#>>'{laboratory_mapping,mapping_status}','')<>'VERIFIED' then
      v_reasons:=array_append(v_reasons,format('STUDY_%s_LAB_MAPPING_NOT_VERIFIED',v_record->>'stability_study_id'));
    end if;
    v_records:=v_records||jsonb_build_array(v_record);
  end loop;

  if v_count=0 then
    v_reasons:=array_append(v_reasons,'NO_GOVERNED_QC_RECORDS');
  end if;

  v_hash:=encode(extensions.digest(convert_to(jsonb_build_object(
    'product_id',p_product_id,
    'workflow_row_version',v_workflow.row_version,
    'composition_stage_row_version',case when v_comp.product_id is null then null else v_comp.row_version end,
    'records',v_records
  )::text,'UTF8'),'sha256'),'hex');

  return jsonb_build_object(
    'product_id',p_product_id,
    'workflow_row_version',v_workflow.row_version,
    'product_entry_status',v_workflow.entry_status,
    'composition_stage_status',case when v_comp.product_id is null then null else v_comp.stage_status end,
    'composition_stage_row_version',case when v_comp.product_id is null then null else v_comp.row_version end,
    'portal_product_ref',v_workflow.portal_product_ref,
    'content_hash',v_hash,
    'qc_records',v_records,
    'governed_record_ids',v_ids,
    'governed_record_count',v_count,
    'ready',coalesce(array_length(v_reasons,1),0)=0,
    'reasons',to_jsonb(v_reasons)
  );
end
$$;

create or replace function public.rpc_eaushadhi_qc_execution_preflight(p_product_id integer)
returns jsonb
language plpgsql
security definer
set search_path to 'public','regulatory','extensions','pg_temp'
as $$
declare
  v_actor uuid;
  v_workflow regulatory.eaushadhi_product_workflow%rowtype;
  v_stage regulatory.eaushadhi_qc_stage%rowtype;
  v_snapshot jsonb;
begin
  v_actor:=public.rpc_eaushadhi_require_permission(false);
  select * into v_workflow from regulatory.eaushadhi_product_workflow where product_id=p_product_id;
  if not found then raise exception using errcode='P0002',message='e-Aushadhi product workflow not found'; end if;
  v_snapshot:=regulatory.eaushadhi_qc_snapshot_v1(p_product_id,v_workflow.row_version);
  select * into v_stage from regulatory.eaushadhi_qc_stage where product_id=p_product_id;

  return jsonb_build_object(
    'product_id',p_product_id,
    'workflow_row_version',v_workflow.row_version,
    'ready',v_snapshot->'ready',
    'reasons',v_snapshot->'reasons',
    'content_hash',v_snapshot->>'content_hash',
    'governed_record_count',(v_snapshot->>'governed_record_count')::integer,
    'governed_record_ids',v_snapshot->'governed_record_ids',
    'product_entry_status',v_snapshot->>'product_entry_status',
    'composition_stage_status',v_snapshot->>'composition_stage_status',
    'composition_stage_row_version',v_snapshot->'composition_stage_row_version',
    'stage',case when found then jsonb_build_object(
      'stage_status',v_stage.stage_status,'row_version',v_stage.row_version,'content_hash',v_stage.content_hash,
      'governed_record_count',v_stage.governed_record_count,'portal_match_count',v_stage.portal_match_count
    ) else null end,
    'active_run',(
      select to_jsonb(x) from (
        select run_id,target_stability_study_id,run_status,current_stage_row_version,content_hash,armed_at
        from regulatory.eaushadhi_qc_run
        where product_id=p_product_id and run_status in ('SAVE_ARMED','SAVE_CONFIRMED','SAVE_AMBIGUOUS')
        order by armed_at desc limit 1
      ) x
    )
  );
end
$$;

create or replace function public.rpc_eaushadhi_qc_run_arm(
  p_product_id integer,
  p_target_stability_study_id bigint,
  p_expected_workflow_row_version bigint,
  p_expected_content_hash text,
  p_expected_stage_row_version bigint,
  p_page_identity_evidence jsonb,
  p_before_list_evidence jsonb,
  p_planner_report jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','regulatory','extensions','pg_temp'
as $$
declare
  v_actor uuid;
  v_workflow regulatory.eaushadhi_product_workflow%rowtype;
  v_comp regulatory.eaushadhi_composition_stage%rowtype;
  v_stage regulatory.eaushadhi_qc_stage%rowtype;
  v_snapshot jsonb;
  v_target jsonb;
  v_run uuid;
  v_now timestamptz:=now();
begin
  v_actor:=public.rpc_eaushadhi_require_permission(true);
  if p_product_id<>262 then raise exception using errcode='42501',message='QC execution V1 is restricted to Product 262'; end if;

  select * into v_workflow from regulatory.eaushadhi_product_workflow where product_id=p_product_id for update;
  if not found then raise exception using errcode='P0002',message='e-Aushadhi product workflow not found'; end if;
  if v_workflow.row_version is distinct from p_expected_workflow_row_version then raise exception using errcode='40001',message='Stale workflow row version'; end if;

  select * into v_comp from regulatory.eaushadhi_composition_stage where product_id=p_product_id;
  if not found or v_comp.stage_status<>'PORTAL_VERIFIED' then raise exception using errcode='55000',message='Composition predecessor is not PORTAL_VERIFIED'; end if;

  v_snapshot:=regulatory.eaushadhi_qc_snapshot_v1(p_product_id,v_workflow.row_version);
  if coalesce((v_snapshot->>'ready')::boolean,false) is not true then raise exception using errcode='55000',message='QC READY v1 server contract is not satisfied'; end if;
  if v_snapshot->>'content_hash' is distinct from p_expected_content_hash then raise exception using errcode='40001',message='QC content hash changed before run arm'; end if;

  select value into v_target from jsonb_array_elements(v_snapshot->'qc_records') x(value)
  where (value->>'stability_study_id')::bigint=p_target_stability_study_id;
  if v_target is null then raise exception using errcode='P0002',message='Target governed QC record not found'; end if;

  if jsonb_typeof(p_page_identity_evidence)<>'object'
     or coalesce(p_page_identity_evidence->>'actualRoute','')<>'/admin/addQCRegister'
     or coalesce(p_page_identity_evidence->>'expectedRoute','')<>'/admin/addQCRegister'
     or coalesce(p_page_identity_evidence->>'actualProductId','')<>p_product_id::text
     or coalesce(p_page_identity_evidence->>'expectedProductId','')<>p_product_id::text
  then raise exception using errcode='22023',message='QC page identity evidence is invalid'; end if;

  if jsonb_typeof(p_before_list_evidence)<>'object'
     or coalesce((p_before_list_evidence->>'settled')::boolean,false) is not true
     or coalesce((p_before_list_evidence->>'success')::boolean,false) is not true
     or coalesce((p_before_list_evidence->>'coverageComplete')::boolean,false) is not true
     or jsonb_typeof(p_before_list_evidence->'rows')<>'array'
  then raise exception using errcode='22023',message='Complete QC before-list evidence is required'; end if;

  if jsonb_typeof(p_planner_report)<>'object'
     or coalesce(p_planner_report->>'code','')<>'OFFLINE_MISSING'
     or coalesce((p_planner_report->>'ok')::boolean,false) is not true
     or coalesce((p_planner_report->>'mutationAllowed')::boolean,true) is not false
     or jsonb_typeof(p_planner_report->'missing')<>'array'
     or not exists (
       select 1 from jsonb_array_elements(p_planner_report->'missing') z
       where (z->>'stabilityStudyId')::bigint=p_target_stability_study_id
     )
  then raise exception using errcode='22023',message='Offline QC planner report is not arm-eligible'; end if;

  if exists (select 1 from regulatory.eaushadhi_qc_run where product_id=p_product_id and run_status in ('SAVE_ARMED','SAVE_CONFIRMED','SAVE_AMBIGUOUS'))
  then raise exception using errcode='23505',message='An active QC run already exists for this product'; end if;

  select * into v_stage from regulatory.eaushadhi_qc_stage where product_id=p_product_id for update;
  if found then
    if v_stage.stage_status='PORTAL_VERIFIED' then raise exception using errcode='55000',message='QC stage is already PORTAL_VERIFIED'; end if;
    if p_expected_stage_row_version is null or v_stage.row_version is distinct from p_expected_stage_row_version then raise exception using errcode='40001',message='Stale QC stage row version'; end if;
    update regulatory.eaushadhi_qc_stage
      set stage_status='PARTIAL',row_version=row_version+1,content_hash=v_snapshot->>'content_hash',
          workflow_row_version=v_workflow.row_version,composition_stage_row_version=v_comp.row_version,
          governed_record_count=(v_snapshot->>'governed_record_count')::integer,
          latest_evidence=jsonb_build_object('event','QC_RUN_ARMED','target_stability_study_id',p_target_stability_study_id,'at',v_now),
          updated_by=v_actor,updated_at=v_now
      where product_id=p_product_id returning * into v_stage;
  else
    if p_expected_stage_row_version is not null then raise exception using errcode='40001',message='QC stage did not exist but expected stage row version was supplied'; end if;
    insert into regulatory.eaushadhi_qc_stage
      (product_id,stage_status,row_version,content_hash,workflow_row_version,composition_stage_row_version,governed_record_count,portal_match_count,latest_evidence,created_by,updated_by)
    values
      (p_product_id,'PARTIAL',1,v_snapshot->>'content_hash',v_workflow.row_version,v_comp.row_version,(v_snapshot->>'governed_record_count')::integer,0,
       jsonb_build_object('event','QC_RUN_ARMED','target_stability_study_id',p_target_stability_study_id,'at',v_now),v_actor,v_actor)
    returning * into v_stage;
  end if;

  insert into regulatory.eaushadhi_qc_run
    (product_id,target_stability_study_id,run_status,start_stage_row_version,current_stage_row_version,
     workflow_row_version,composition_stage_row_version,content_hash,portal_product_ref,
     page_identity_evidence,before_list_evidence,planner_report,target_projection,armed_by)
  values
    (p_product_id,p_target_stability_study_id,'SAVE_ARMED',v_stage.row_version,v_stage.row_version,
     v_workflow.row_version,v_comp.row_version,v_snapshot->>'content_hash',v_workflow.portal_product_ref,
     p_page_identity_evidence,p_before_list_evidence,p_planner_report,v_target,v_actor)
  returning run_id into v_run;

  insert into regulatory.audit_event(entity_schema,entity_table,entity_key,action,new_data,actor_user_id,application_name)
  values('regulatory','eaushadhi_qc_run',v_run::text,'QC_RUN_ARMED',
         jsonb_build_object('product_id',p_product_id,'target_stability_study_id',p_target_stability_study_id,'stage_row_version',v_stage.row_version),
         v_actor,'E_AUSHADHI_AUTOMATION');

  return jsonb_build_object('run_id',v_run,'run_status','SAVE_ARMED','stage_row_version',v_stage.row_version,'target_projection',v_target);
end
$$;

create or replace function public.rpc_eaushadhi_qc_run_record_save(
  p_run_id uuid,
  p_save_outcome text,
  p_save_evidence jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','regulatory','extensions','pg_temp'
as $$
declare v_actor uuid; v_run regulatory.eaushadhi_qc_run%rowtype; v_status text; v_now timestamptz:=now();
begin
  v_actor:=public.rpc_eaushadhi_require_permission(true);
  if p_save_outcome not in ('CONFIRMED','AMBIGUOUS','REJECTED') then raise exception using errcode='22023',message='Invalid QC save outcome'; end if;
  if jsonb_typeof(p_save_evidence)<>'object' then raise exception using errcode='22023',message='QC save evidence must be an object'; end if;

  select * into v_run from regulatory.eaushadhi_qc_run where run_id=p_run_id for update;
  if not found then raise exception using errcode='P0002',message='QC run not found'; end if;
  if v_run.run_status<>'SAVE_ARMED' then raise exception using errcode='55000',message='QC run is not SAVE_ARMED'; end if;

  v_status:=case p_save_outcome when 'CONFIRMED' then 'SAVE_CONFIRMED' when 'AMBIGUOUS' then 'SAVE_AMBIGUOUS' else 'SAVE_REJECTED' end;
  update regulatory.eaushadhi_qc_run
  set run_status=v_status,save_outcome=p_save_outcome,save_evidence=p_save_evidence,
      save_recorded_by=v_actor,save_recorded_at=v_now,updated_at=v_now
  where run_id=p_run_id returning * into v_run;

  insert into regulatory.audit_event(entity_schema,entity_table,entity_key,action,new_data,actor_user_id,application_name)
  values('regulatory','eaushadhi_qc_run',p_run_id::text,'QC_SAVE_OUTCOME_RECORDED',
         jsonb_build_object('product_id',v_run.product_id,'target_stability_study_id',v_run.target_stability_study_id,'save_outcome',p_save_outcome),
         v_actor,'E_AUSHADHI_AUTOMATION');

  return jsonb_build_object('run_id',p_run_id,'run_status',v_status,'save_outcome',p_save_outcome);
end
$$;

create or replace function public.rpc_eaushadhi_qc_run_verify_row(
  p_run_id uuid,
  p_after_list_evidence jsonb,
  p_reread_evidence jsonb,
  p_document_reread_evidence jsonb,
  p_verify_report jsonb,
  p_resolved_portal_row_id text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','regulatory','extensions','pg_temp'
as $$
declare
  v_actor uuid; v_run regulatory.eaushadhi_qc_run%rowtype; v_workflow regulatory.eaushadhi_product_workflow%rowtype;
  v_snapshot jsonb; v_target jsonb; v_stage regulatory.eaushadhi_qc_stage%rowtype; v_now timestamptz:=now();
begin
  v_actor:=public.rpc_eaushadhi_require_permission(true);
  select * into v_run from regulatory.eaushadhi_qc_run where run_id=p_run_id for update;
  if not found then raise exception using errcode='P0002',message='QC run not found'; end if;
  if v_run.run_status not in ('SAVE_CONFIRMED','SAVE_AMBIGUOUS') then raise exception using errcode='55000',message='QC run is not row-verifiable'; end if;

  select * into v_workflow from regulatory.eaushadhi_product_workflow where product_id=v_run.product_id;
  v_snapshot:=regulatory.eaushadhi_qc_snapshot_v1(v_run.product_id,v_workflow.row_version);
  if v_snapshot->>'content_hash' is distinct from v_run.content_hash then raise exception using errcode='40001',message='QC content hash changed before row verification'; end if;
  select value into v_target from jsonb_array_elements(v_snapshot->'qc_records') x(value)
  where (value->>'stability_study_id')::bigint=v_run.target_stability_study_id;
  if v_target is null or v_target is distinct from v_run.target_projection then raise exception using errcode='40001',message='QC target projection changed before row verification'; end if;

  if jsonb_typeof(p_after_list_evidence)<>'object'
     or coalesce((p_after_list_evidence->>'success')::boolean,false) is not true
     or coalesce((p_after_list_evidence->>'coverageComplete')::boolean,false) is not true
  then raise exception using errcode='22023',message='Fresh complete QC after-list evidence is required'; end if;

  if jsonb_typeof(p_reread_evidence)<>'object'
     or coalesce((p_reread_evidence->>'success')::boolean,false) is not true
     or p_reread_evidence->'observedProjection' is distinct from v_target
  then raise exception using errcode='22023',message='Native QC reread does not exactly match governed target'; end if;

  if jsonb_typeof(p_document_reread_evidence)<>'object'
     or coalesce((p_document_reread_evidence->>'success')::boolean,false) is not true
     or nullif(p_document_reread_evidence->>'contentSha256','') is distinct from nullif(v_target#>>'{document,content_sha256}','')
  then raise exception using errcode='22023',message='QC test-report reread does not match governed document'; end if;

  if jsonb_typeof(p_verify_report)<>'object'
     or coalesce((p_verify_report->>'ok')::boolean,false) is not true
     or coalesce((p_verify_report->>'exactMatch')::boolean,false) is not true
     or (p_verify_report->>'stabilityStudyId')::bigint is distinct from v_run.target_stability_study_id
  then raise exception using errcode='22023',message='QC verify report is not exact-match eligible'; end if;

  update regulatory.eaushadhi_qc_run
  set run_status='ROW_VERIFIED',after_list_evidence=p_after_list_evidence,reread_evidence=p_reread_evidence,
      document_reread_evidence=p_document_reread_evidence,verify_report=p_verify_report,
      resolved_portal_row_id=nullif(btrim(p_resolved_portal_row_id),''),
      row_verified_by=v_actor,row_verified_at=v_now,updated_at=v_now
  where run_id=p_run_id returning * into v_run;

  select * into v_stage from regulatory.eaushadhi_qc_stage where product_id=v_run.product_id for update;
  update regulatory.eaushadhi_qc_stage
  set row_version=row_version+1,
      portal_match_count=least(governed_record_count,portal_match_count+1),
      latest_evidence=jsonb_build_object('event','QC_ROW_VERIFIED','run_id',p_run_id,'target_stability_study_id',v_run.target_stability_study_id,'at',v_now),
      updated_by=v_actor,updated_at=v_now
  where product_id=v_run.product_id returning * into v_stage;

  update regulatory.eaushadhi_qc_run set current_stage_row_version=v_stage.row_version where run_id=p_run_id;

  insert into regulatory.audit_event(entity_schema,entity_table,entity_key,action,new_data,actor_user_id,application_name)
  values('regulatory','eaushadhi_qc_run',p_run_id::text,'QC_ROW_VERIFIED',
         jsonb_build_object('product_id',v_run.product_id,'target_stability_study_id',v_run.target_stability_study_id,'stage_row_version',v_stage.row_version),
         v_actor,'E_AUSHADHI_AUTOMATION');

  return jsonb_build_object('run_id',p_run_id,'run_status','ROW_VERIFIED','stage_row_version',v_stage.row_version);
end
$$;

create or replace function public.rpc_eaushadhi_qc_stage_mark_portal_verified(
  p_product_id integer,
  p_expected_stage_row_version bigint,
  p_expected_content_hash text,
  p_final_list_evidence jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','regulatory','extensions','pg_temp'
as $$
declare
  v_actor uuid; v_workflow regulatory.eaushadhi_product_workflow%rowtype; v_stage regulatory.eaushadhi_qc_stage%rowtype;
  v_snapshot jsonb; v_expected_ids bigint[]; v_observed_ids bigint[]; v_now timestamptz:=now();
begin
  v_actor:=public.rpc_eaushadhi_require_permission(true);
  if p_product_id<>262 then raise exception using errcode='42501',message='QC stage verification V1 is restricted to Product 262'; end if;

  select * into v_workflow from regulatory.eaushadhi_product_workflow where product_id=p_product_id;
  select * into v_stage from regulatory.eaushadhi_qc_stage where product_id=p_product_id for update;
  if not found then raise exception using errcode='P0002',message='QC stage not found'; end if;
  if v_stage.stage_status<>'PARTIAL' then raise exception using errcode='55000',message='QC stage must be PARTIAL before final verification'; end if;
  if v_stage.row_version is distinct from p_expected_stage_row_version then raise exception using errcode='40001',message='Stale QC stage row version'; end if;

  v_snapshot:=regulatory.eaushadhi_qc_snapshot_v1(p_product_id,v_workflow.row_version);
  if coalesce((v_snapshot->>'ready')::boolean,false) is not true then raise exception using errcode='55000',message='QC READY v1 server contract is not satisfied'; end if;
  if v_snapshot->>'content_hash' is distinct from p_expected_content_hash
     or v_stage.content_hash is distinct from p_expected_content_hash
  then raise exception using errcode='40001',message='QC content hash changed before final-stage verification'; end if;

  if exists(select 1 from regulatory.eaushadhi_qc_run where product_id=p_product_id and run_status in ('SAVE_ARMED','SAVE_CONFIRMED','SAVE_AMBIGUOUS'))
  then raise exception using errcode='55000',message='Active QC run blocks final-stage verification'; end if;

  if jsonb_typeof(p_final_list_evidence)<>'object'
     or coalesce((p_final_list_evidence->>'success')::boolean,false) is not true
     or coalesce((p_final_list_evidence->>'coverageComplete')::boolean,false) is not true
     or jsonb_typeof(p_final_list_evidence->'matchedStudyIds')<>'array'
  then raise exception using errcode='22023',message='Fresh complete QC final-list evidence is required'; end if;

  select coalesce(array_agg((x.value)::bigint order by (x.value)::bigint),array[]::bigint[]) into v_expected_ids
  from jsonb_array_elements(v_snapshot->'governed_record_ids') x(value);
  select coalesce(array_agg((x.value)::bigint order by (x.value)::bigint),array[]::bigint[]) into v_observed_ids
  from jsonb_array_elements(p_final_list_evidence->'matchedStudyIds') x(value);
  if v_expected_ids is distinct from v_observed_ids then raise exception using errcode='22023',message='QC final portal set does not exactly match governed study IDs'; end if;

  if exists (
    select 1 from unnest(v_expected_ids) sid
    where not exists (
      select 1 from regulatory.eaushadhi_qc_run r
      where r.product_id=p_product_id and r.target_stability_study_id=sid and r.run_status='ROW_VERIFIED'
    )
  ) then raise exception using errcode='55000',message='Every governed QC record must have ROW_VERIFIED evidence'; end if;

  update regulatory.eaushadhi_qc_stage
  set stage_status='PORTAL_VERIFIED',row_version=row_version+1,
      portal_match_count=(v_snapshot->>'governed_record_count')::integer,
      latest_evidence=jsonb_build_object('event','QC_STAGE_PORTAL_VERIFIED','matched_study_ids',to_jsonb(v_expected_ids),'at',v_now),
      portal_verified_by=v_actor,portal_verified_at=v_now,updated_by=v_actor,updated_at=v_now
  where product_id=p_product_id returning * into v_stage;

  insert into regulatory.audit_event(entity_schema,entity_table,entity_key,action,new_data,actor_user_id,application_name)
  values('regulatory','eaushadhi_qc_stage',p_product_id::text,'QC_STAGE_PORTAL_VERIFIED',
         jsonb_build_object('product_id',p_product_id,'stage_row_version',v_stage.row_version,'governed_record_count',v_stage.governed_record_count),
         v_actor,'E_AUSHADHI_AUTOMATION');

  return jsonb_build_object('product_id',p_product_id,'stage_status',v_stage.stage_status,'stage_row_version',v_stage.row_version,'portal_match_count',v_stage.portal_match_count);
end
$$;

revoke all on function regulatory.eaushadhi_qc_snapshot_v1(integer,bigint) from public,anon,authenticated;
revoke all on function public.rpc_eaushadhi_qc_execution_preflight(integer) from public,anon;
revoke all on function public.rpc_eaushadhi_qc_run_arm(integer,bigint,bigint,text,bigint,jsonb,jsonb,jsonb) from public,anon;
revoke all on function public.rpc_eaushadhi_qc_run_record_save(uuid,text,jsonb) from public,anon;
revoke all on function public.rpc_eaushadhi_qc_run_verify_row(uuid,jsonb,jsonb,jsonb,jsonb,text) from public,anon;
revoke all on function public.rpc_eaushadhi_qc_stage_mark_portal_verified(integer,bigint,text,jsonb) from public,anon;

grant execute on function public.rpc_eaushadhi_qc_execution_preflight(integer) to authenticated,service_role;
grant execute on function public.rpc_eaushadhi_qc_run_arm(integer,bigint,bigint,text,bigint,jsonb,jsonb,jsonb) to authenticated,service_role;
grant execute on function public.rpc_eaushadhi_qc_run_record_save(uuid,text,jsonb) to authenticated,service_role;
grant execute on function public.rpc_eaushadhi_qc_run_verify_row(uuid,jsonb,jsonb,jsonb,jsonb,text) to authenticated,service_role;
grant execute on function public.rpc_eaushadhi_qc_stage_mark_portal_verified(integer,bigint,text,jsonb) to authenticated,service_role;
grant execute on function regulatory.eaushadhi_qc_snapshot_v1(integer,bigint) to service_role;
