-- SOURCE-CONTROL PARITY
-- Company sales-allocation default policy foundation already exists live
-- (costing.sales_allocation_default_policy + GET/SET/as-of) without a prior
-- matching repository migration file.
--
-- DO NOT reapply to production. Production already has this table and RPCs.
-- This file exists for repository schema history / fresh-env bootstrap only.
-- Uses IF NOT EXISTS / CREATE OR REPLACE so accidental apply is non-destructive
-- for an already-aligned database.

create table if not exists costing.sales_allocation_default_policy (
  id bigint generated by default as identity primary key,
  scenario_code text not null,
  default_sales_units numeric not null,
  effective_from date not null,
  effective_to date,
  status text not null default 'APPROVED'::text,
  reason text not null,
  approval_reference text,
  previous_policy_id bigint references costing.sales_allocation_default_policy(id),
  created_at timestamptz not null default clock_timestamp(),
  created_by uuid default auth.uid(),
  closed_at timestamptz,
  closed_by uuid,
  cancelled_at timestamptz,
  cancelled_by uuid,
  cancellation_reason text,
  cancellation_approval_reference text,
  constraint sales_allocation_default_policy_dates_chk
    check (effective_to is null or effective_to >= effective_from),
  constraint sales_allocation_default_policy_reason_chk
    check (length(btrim(reason)) > 0),
  constraint sales_allocation_default_policy_scenario_chk
    check (scenario_code = any (array['NEW_SKU_EXISTING_PRODUCT'::text, 'NEW_PRODUCT_NO_HISTORY'::text])),
  constraint sales_allocation_default_policy_status_chk
    check (status = any (array['APPROVED'::text, 'CLOSED'::text, 'CANCELLED'::text])),
  constraint sales_allocation_default_policy_units_chk
    check (default_sales_units > 0::numeric)
);

create unique index if not exists uq_sales_allocation_default_policy_open
  on costing.sales_allocation_default_policy (scenario_code)
  where status = 'APPROVED' and effective_to is null;

create index if not exists idx_sales_allocation_default_policy_dates
  on costing.sales_allocation_default_policy (effective_from, effective_to);
create index if not exists idx_sales_allocation_default_policy_scenario
  on costing.sales_allocation_default_policy (scenario_code);
create index if not exists idx_sales_allocation_default_policy_status
  on costing.sales_allocation_default_policy (status);

comment on table costing.sales_allocation_default_policy is
  'SOURCE-CONTROL PARITY: company CSA default units. Authoritative after csa_scenario_owned_fallback cutover.';
