create table if not exists costing.regional_marketing_evidence_acceptance (
  id bigint generated by default as identity primary key,
  period_start date not null,
  source_valuation_date date not null,
  source_refresh_run_id bigint not null references costing.costing_refresh_run(id),
  regional_basis_snapshot_id bigint not null references costing.sku_regional_marketing_allocation_basis_snapshot(id),
  regional_marketing_snapshot_id bigint not null references costing.sku_regional_marketing_expense_allocation_snapshot(id),
  sku_id bigint not null,
  product_id bigint not null,
  region_code text not null check (region_code in ('IK','OK')),
  regional_basis_source text not null,
  regional_basis_status text not null,
  resolved_regional_units numeric,
  resolved_regional_base_qty numeric,
  regional_assumption_id bigint,
  regional_default_policy_id bigint,
  regional_default_scenario text,
  marketing_value_source text not null,
  resolved_product_region_marketing_sales_value numeric,
  marketing_expense_cost_per_sku_region numeric,
  evidence_fingerprint text not null,
  acceptance_status text not null default 'ACTIVE' check (acceptance_status in ('ACTIVE','INACTIVE')),
  acceptance_reason text not null,
  acceptance_note text,
  accepted_by uuid not null,
  accepted_at timestamptz not null default clock_timestamp(),
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  unique(period_start,source_valuation_date,sku_id,region_code,evidence_fingerprint)
);

create index if not exists ix_regional_marketing_evidence_acceptance_match
on costing.regional_marketing_evidence_acceptance(period_start,source_valuation_date,sku_id,region_code,evidence_fingerprint,acceptance_status);

create or replace function costing.fn_regional_marketing_evidence_fingerprint(
  p_sku_id bigint,
  p_product_id bigint,
  p_region_code text,
  p_valuation_date date,
  p_regional_basis_source text,
  p_resolved_regional_units numeric,
  p_resolved_regional_base_qty numeric,
  p_regional_assumption_id bigint,
  p_regional_default_policy_id bigint,
  p_regional_default_scenario text,
  p_marketing_value_source text,
  p_resolved_product_region_marketing_sales_value numeric,
  p_marketing_expense_cost_per_sku_region numeric
) returns text
language sql immutable
as $f$
select md5(concat_ws('|',
  coalesce(p_sku_id::text,'∅'),coalesce(p_product_id::text,'∅'),coalesce(upper(btrim(p_region_code)),'∅'),
  coalesce(p_valuation_date::text,'∅'),coalesce(p_regional_basis_source,'∅'),
  coalesce(p_resolved_regional_units::text,'∅'),coalesce(p_resolved_regional_base_qty::text,'∅'),
  coalesce(p_regional_assumption_id::text,'∅'),coalesce(p_regional_default_policy_id::text,'∅'),
  coalesce(p_regional_default_scenario,'∅'),coalesce(p_marketing_value_source,'∅'),
  coalesce(p_resolved_product_region_marketing_sales_value::text,'∅'),
  coalesce(p_marketing_expense_cost_per_sku_region::text,'∅')
));
$f$;

create or replace function costing.fn_regional_marketing_review_status(p_regional_marketing_snapshot_id bigint)
returns table(raw_status text,effective_status text,acceptance_id bigint,evidence_fingerprint text,is_acceptance_eligible boolean)
language sql stable security definer
set search_path to 'costing','public','pg_temp'
as $f$
with s as (
  select e.*,b.regional_assumption_id,b.regional_default_policy_id,b.regional_default_scenario,
    costing.fn_regional_marketing_evidence_fingerprint(
      e.sku_id,e.product_id,e.region_code,e.valuation_date,e.regional_basis_source,
      e.resolved_regional_units,e.resolved_regional_base_qty,b.regional_assumption_id,
      b.regional_default_policy_id,b.regional_default_scenario,e.marketing_value_source,
      e.resolved_product_region_marketing_sales_value,e.marketing_expense_cost_per_sku_region
    ) fp,
    (
      e.marketing_expense_allocation_status='REVIEW_REQUIRED'
      and (
        e.regional_basis_source in ('REGION_SCALED_COMMON_BASIS','REGIONAL_DEFAULT_POLICY_UNITS','REGIONAL_ASSUMPTION_UNITS')
        or e.marketing_value_source in ('GOVERNED_REGIONAL_DEFAULT','APPROVED_REGIONAL_ASSUMPTION')
      )
      and not (e.marketing_value_source='ACTUAL_SIGNED_BILLED_SALES' and coalesce(e.resolved_product_region_marketing_sales_value,0)<=0)
    ) eligible
  from costing.sku_regional_marketing_expense_allocation_snapshot e
  join costing.sku_regional_marketing_allocation_basis_snapshot b on b.id=e.regional_basis_snapshot_id
  where e.id=p_regional_marketing_snapshot_id
), a as (
  select a.id
  from s join costing.regional_marketing_evidence_acceptance a
    on a.period_start=s.period_start
   and a.source_valuation_date=s.valuation_date
   and a.sku_id=s.sku_id
   and a.region_code=s.region_code
   and a.evidence_fingerprint=s.fp
   and a.acceptance_status='ACTIVE'
  order by a.accepted_at desc,a.id desc limit 1
)
select s.marketing_expense_allocation_status,
       case when s.marketing_expense_allocation_status='REVIEW_REQUIRED' and s.eligible and a.id is not null then 'READY'
            else s.marketing_expense_allocation_status end,
       a.id,s.fp,s.eligible
from s left join a on true;
$f$;

create or replace view costing.v_regional_marketing_evidence_review_queue as
select e.period_start,e.valuation_date,e.refresh_run_id,e.id regional_marketing_snapshot_id,
       e.regional_basis_snapshot_id,e.sku_id,e.product_id,e.product_name,e.region_code,
       e.regional_basis_source,e.regional_basis_status,e.resolved_regional_units,e.resolved_regional_base_qty,
       b.regional_assumption_id,b.regional_assumption_basis,b.regional_default_policy_id,b.regional_default_scenario,
       b.regional_default_sales_units,b.regional_default_assumed_sales_value,
       e.marketing_value_source,e.resolved_product_region_marketing_sales_value,
       e.marketing_expense_cost_per_sku_region,e.marketing_expense_allocation_status raw_status,
       rs.effective_status,rs.is_acceptance_eligible,rs.acceptance_id,rs.evidence_fingerprint,
       (rs.acceptance_id is not null) is_accepted
from costing.sku_regional_marketing_expense_allocation_snapshot e
join costing.sku_regional_marketing_allocation_basis_snapshot b on b.id=e.regional_basis_snapshot_id
cross join lateral costing.fn_regional_marketing_review_status(e.id) rs
where e.marketing_expense_allocation_status='REVIEW_REQUIRED';

create or replace function costing.rpc_accept_regional_marketing_review(
  p_refresh_run_id bigint,p_sku_id bigint,p_region_code text,p_acceptance_reason text,p_acceptance_note text default null
) returns table(acceptance_id bigint,refresh_run_id bigint,sku_id bigint,region_code text,evidence_fingerprint text,effective_status text)
language plpgsql security definer
set search_path to 'costing','public','pg_temp'
as $f$
#variable_conflict use_column
declare
  v_uid uuid:=auth.uid(); v_q record; v_id bigint;
begin
  perform public.require_permission('module:costing-control-center',true);
  if p_acceptance_reason is null or btrim(p_acceptance_reason)='' then raise exception 'Acceptance reason is required'; end if;
  select * into v_q from costing.v_regional_marketing_evidence_review_queue q
   where q.refresh_run_id=p_refresh_run_id and q.sku_id=p_sku_id and q.region_code=upper(btrim(p_region_code));
  if not found then raise exception 'Regional Marketing review row not found for run %, SKU %, region %',p_refresh_run_id,p_sku_id,p_region_code; end if;
  if not v_q.is_acceptance_eligible then raise exception 'Regional Marketing evidence is not acceptance-eligible for run %, SKU %, region %. Raw source/value must be reviewed separately.',p_refresh_run_id,p_sku_id,p_region_code; end if;
  insert into costing.regional_marketing_evidence_acceptance(
    period_start,source_valuation_date,source_refresh_run_id,regional_basis_snapshot_id,regional_marketing_snapshot_id,
    sku_id,product_id,region_code,regional_basis_source,regional_basis_status,resolved_regional_units,resolved_regional_base_qty,
    regional_assumption_id,regional_default_policy_id,regional_default_scenario,marketing_value_source,
    resolved_product_region_marketing_sales_value,marketing_expense_cost_per_sku_region,evidence_fingerprint,
    acceptance_status,acceptance_reason,acceptance_note,accepted_by,accepted_at,updated_at
  ) values (
    v_q.period_start,v_q.valuation_date,p_refresh_run_id,v_q.regional_basis_snapshot_id,v_q.regional_marketing_snapshot_id,
    v_q.sku_id,v_q.product_id,v_q.region_code,v_q.regional_basis_source,v_q.regional_basis_status,v_q.resolved_regional_units,v_q.resolved_regional_base_qty,
    v_q.regional_assumption_id,v_q.regional_default_policy_id,v_q.regional_default_scenario,v_q.marketing_value_source,
    v_q.resolved_product_region_marketing_sales_value,v_q.marketing_expense_cost_per_sku_region,v_q.evidence_fingerprint,
    'ACTIVE',p_acceptance_reason,p_acceptance_note,v_uid,clock_timestamp(),clock_timestamp()
  )
  on conflict(period_start,source_valuation_date,sku_id,region_code,evidence_fingerprint)
  do update set acceptance_status='ACTIVE',acceptance_reason=excluded.acceptance_reason,acceptance_note=excluded.acceptance_note,
                accepted_by=excluded.accepted_by,accepted_at=clock_timestamp(),updated_at=clock_timestamp(),
                source_refresh_run_id=excluded.source_refresh_run_id,regional_basis_snapshot_id=excluded.regional_basis_snapshot_id,
                regional_marketing_snapshot_id=excluded.regional_marketing_snapshot_id
  returning id into v_id;
  return query select v_id,p_refresh_run_id,p_sku_id,upper(btrim(p_region_code)),v_q.evidence_fingerprint,'READY'::text;
end;
$f$;

revoke all on function costing.rpc_accept_regional_marketing_review(bigint,bigint,text,text,text) from public,anon;
grant execute on function costing.rpc_accept_regional_marketing_review(bigint,bigint,text,text,text) to authenticated;
grant select on costing.v_regional_marketing_evidence_review_queue to authenticated;
